import { useLayoutEffect, useRef, useState } from 'react';
import { addDays,addMonths,dateAllowed,daysInMonth,parseDate,weekday } from '../lib/date-utils';
import { cn } from '../lib/cn';
type Props={month:string;value?:string;onSelect:(day:string)=>void;onMonthChange:(month:string)=>void;min?:string;max?:string;disabledDates?:readonly string[];range?:{start:string;end:string};onHover?:(day:string)=>void;autoFocus?:boolean};
export function CalendarGrid({month,value,onSelect,onMonthChange,min,max,disabledDates=[],range,onHover,autoFocus=false}:Props){
 const root=useRef<HTMLDivElement>(null),pending=useRef<string|null>(null),initial=useRef(autoFocus);const first=month+'-01',parts=parseDate(first)!;const cells=Array.from({length:42},(_,index)=>{const offset=index-weekday(first),day=addDays(first,offset);return offset!==0&&day===first?'':day;});const allowed=(day:string)=>dateAllowed(day,min,max,disabledDates);const initialDay=cells.find(day=>day.slice(0,7)===month&&allowed(day))??first;const [focus,setFocus]=useState(value&&allowed(value)?value:initialDay);
 useLayoutEffect(()=>{const target=pending.current??(value?.slice(0,7)===month&&allowed(value)?value:initialDay);setFocus(target);if(pending.current||initial.current)root.current?.querySelector<HTMLButtonElement>(`[data-day="${target}"]`)?.focus();pending.current=null;initial.current=false;},[month,value,min,max,disabledDates.join('|')]);
 const move=(from:string,key:string,shift:boolean)=>{let next=from;if(key==='ArrowLeft')next=addDays(from,-1);else if(key==='ArrowRight')next=addDays(from,1);else if(key==='ArrowUp')next=addDays(from,-7);else if(key==='ArrowDown')next=addDays(from,7);else if(key==='Home')next=addDays(from,-weekday(from));else if(key==='End')next=addDays(from,6-weekday(from));else if(key==='PageUp')next=addMonths(from,shift?-12:-1);else if(key==='PageDown')next=addMonths(from,shift?12:1);else return false;const direction=next<from?-1:1;for(let tries=0;tries<366&&!allowed(next);tries++){const candidate=addDays(next,direction);if(candidate===next)return true;next=candidate;}if(!allowed(next)||next===from)return true;setFocus(next);pending.current=next;if(next.slice(0,7)!==month)onMonthChange(next.slice(0,7));else{root.current?.querySelector<HTMLButtonElement>(`[data-day="${next}"]`)?.focus();pending.current=null;}return true;};
 return <div ref={root} role="grid" aria-label={`${parts.year}년 ${parts.month}월 날짜`} onMouseLeave={()=>onHover?.('')} onKeyDown={event=>{const day=(event.target as HTMLElement).closest<HTMLButtonElement>('[data-day]')?.dataset.day;if(day&&move(day,event.key,event.shiftKey))event.preventDefault();}}><div role="row" className="grid grid-cols-7 gap-1">{['일','월','화','수','목','금','토'].map(day=><span role="columnheader" key={day} className="py-2 text-center text-g-small text-g-soft">{day}</span>)}</div>{Array.from({length:6},(_,week)=><div role="row" key={week} className="grid grid-cols-7 gap-1">{cells.slice(week*7,week*7+7).map((day,index)=>{if(!day)return <span key={week+'-'+index} role="gridcell" aria-hidden="true"/>;const current=day===value,within=Boolean(range?.start&&range.end&&day>=range.start&&day<=range.end);return <button key={week+'-'+index} role="gridcell" data-day={day} type="button" aria-label={day} aria-selected={current} disabled={!allowed(day)} tabIndex={day===focus?0:-1} onFocus={()=>setFocus(day)} onMouseEnter={()=>onHover?.(day)} onClick={()=>onSelect(day)} className={cn('border-0 min-h-11 min-w-0 rounded-g-control text-g-small focus-visible:outline-3 focus-visible:outline-g-focus disabled:opacity-40',current?'bg-g-action text-g-on-action':within?'bg-g-muted text-g-ink':'bg-transparent hover:bg-g-muted',day.slice(0,7)!==month&&!current&&'text-g-soft')}>{parseDate(day)?.day}</button>;})}</div>)}</div>;
}
