import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import test from 'node:test';
const MODE='source';
const repo=path.resolve(new URL('../../..',import.meta.url).pathname),evidence=process.env.CORE09_EVIDENCE_DIR,packageRoot=process.env.CORE09_PACKAGE_ROOT;
assert.ok(evidence&&path.isAbsolute(evidence)&&!path.resolve(evidence).startsWith(repo+'/'),'CORE09_EVIDENCE_DIR must be absolute outside the repository');
assert.ok(packageRoot&&path.isAbsolute(packageRoot)&&!path.resolve(packageRoot).startsWith(repo+'/')&&!fs.realpathSync(packageRoot).startsWith(repo+'/'),'CORE09_PACKAGE_ROOT must point to the current scratch-built package');
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex'),artifact=JSON.parse(fs.readFileSync(path.join(evidence,'boundary/artifact.json'))),manifest=JSON.parse(fs.readFileSync(path.join(packageRoot,'payload/manifest.json')));
assert.equal(hash(fs.readFileSync(artifact.tarball)),artifact.sha256);
for(const [source,target] of [['router.mjs','router.mjs'],['doctor.mjs','doctor.mjs']])if(fs.existsSync(path.join(repo,'packages/core/src',source)))assert.equal(hash(fs.readFileSync(path.join(packageRoot,'dist',target))),hash(fs.readFileSync(path.join(repo,'packages/core/src',source))),'Rebuild the scratch package before testing canonical '+source);
function snapshot(root){const rootStat=fs.lstatSync(root,{bigint:true}),result={'.':{inode:String(rootStat.ino),mtimeNs:String(rootStat.mtimeNs),mode:String(rootStat.mode),kind:'directory'}};function visit(dir){for(const name of fs.readdirSync(dir).sort()){const full=path.join(dir,name),relative=path.relative(root,full).split(path.sep).join('/'),s=fs.lstatSync(full,{bigint:true});result[relative]={inode:String(s.ino),mtimeNs:String(s.mtimeNs),mode:String(s.mode),kind:s.isSymbolicLink()?'link':s.isDirectory()?'directory':'file',...(s.isSymbolicLink()?{link:fs.readlinkSync(full)}:s.isFile()?{hash:hash(fs.readFileSync(full)),bytes:Number(s.size)}:{})};if(s.isDirectory())visit(full);}}visit(root);return result;}
function run(label,command,args,cwd,env=process.env){const before=snapshot(cwd),started=new Date().toISOString(),start=performance.now(),r=spawnSync(command,args,{cwd,env,encoding:'utf8',maxBuffer:32e6}),after=snapshot(cwd);fs.writeFileSync(path.join(evidence,'doctor-'+MODE+'-'+label+'-'+process.hrtime.bigint()+'.json'),JSON.stringify({argv:[command,...args],cwd,runtime:process.version,started,ended:new Date().toISOString(),durationMs:performance.now()-start,exit:r.status,stdout:r.stdout,stderr:r.stderr,before,after},null,2));return {...r,before,after};}
function prepare(label,{initialized=true,component=true}={}){const host=fs.mkdtempSync(path.join(evidence,'doctor-'+MODE+'-'+label+'-'));fs.writeFileSync(path.join(host,'package.json'),JSON.stringify({name:'doctor-host',private:true,type:'module',scripts:{build:'vite build'},dependencies:{react:'19.2.0','react-dom':'19.2.0',...manifest.runtime},devDependencies:{vite:'7.3.6',...manifest.build,...manifest.types}}));const install=run('prepare-install','npm',['install','--offline','--ignore-scripts','--save-dev','--save-exact',artifact.tarball],host);assert.equal(install.status,0,install.stderr);const physical=path.join(host,'node_modules/@orderthan31/hangyeol-core'),bin=MODE==='physical'?path.join(host,'node_modules/.bin/hangyeol'):path.join(packageRoot,'bin/hangyeol.mjs');assert.equal(fs.lstatSync(physical).isSymbolicLink(),false);assert.equal(fs.realpathSync(path.join(host,'node_modules/.bin/hangyeol')),path.join(physical,'bin/hangyeol.mjs'));const lock=JSON.parse(fs.readFileSync(path.join(host,'package-lock.json'))),record=lock.packages['node_modules/@orderthan31/hangyeol-core'];assert.equal(record.version,artifact.version);assert.equal(record.integrity,artifact.integrity);assert.equal(record.dev,true);assert.ok(!record.link);if(initialized){fs.mkdirSync(path.join(host,'styles'));fs.writeFileSync(path.join(host,'styles/theme.css'),'.host-sentinel { color: rebeccapurple; }\n');const init=run('prepare-init',bin,['init','--source-root','ui/system','--style-path','styles/theme.css','--public-root','static','--font-path','assets/type','--base-path','/design/','--alias','@hangyeol'],host);assert.equal(init.status,0,init.stderr);if(component){const add=run('prepare-add',bin,['add','text-field'],host);assert.equal(add.status,0,add.stderr);}}
const trap=path.join(evidence,'npm-trap-'+MODE+'-'+path.basename(host)),trace=path.join(evidence,'npm-trace-'+path.basename(host)+'.txt');fs.mkdirSync(trap);fs.writeFileSync(trace,'');fs.writeFileSync(path.join(trap,'npm'),'#!'+process.execPath+'\nimport fs from "node:fs"; fs.appendFileSync('+JSON.stringify(trace)+',JSON.stringify(process.argv.slice(2))+"\\n");process.exit(97);\n',{mode:0o755});const env={...process.env,PATH:trap+path.delimiter+process.env.PATH},probe=run('npm-guard-injection-proof',path.join(trap,'npm'),['--version'],host,env);assert.equal(probe.status,97,'The fake npm injection guard must actually execute');assert.ok(fs.readFileSync(trace,'utf8').includes('--version'));fs.writeFileSync(trace,'');return {host,bin,physical,record,trace,env};}
function doctor(f,label,expected){const r=run(label,f.bin,['doctor'],f.host,f.env);assert.deepEqual(r.after,r.before,'doctor must preserve complete consumer bytes/inodes/mtime/modes/links');assert.equal(fs.readFileSync(f.trace,'utf8'),'','doctor must never invoke npm');assert.equal(r.status,expected,'doctor diagnostic exit: '+r.stderr);assert.match(r.stdout,/^\s*\{/,'doctor must return structured diagnostics, not unsupported-command text');const report=JSON.parse(r.stdout);assert.equal(report.operation,'doctor');assert.equal(report.readOnly,true);assert.equal(report.exit,expected);return report;}

test('doctor recognizes initialized custom-path consumer without treating authored helper edits as corruption',()=>{const f=prepare('normal'),config=path.join(f.host,'hangyeol.json'),cn=path.join(f.host,'ui/system/lib/cn.ts'),c=JSON.parse(fs.readFileSync(config));c.owner={kept:7};c.tokens={palette:'Owner',source:'ui/system/owner.json'};fs.writeFileSync(config,JSON.stringify(c));fs.appendFileSync(cn,'\n// editable owner helper\n');const report=doctor(f,'normal',0);assert.equal(report.status,'ok');assert.equal(report.config.sourceRoot,'ui/system');assert.ok(report.checks.some(x=>x.code==='source.edited'&&x.path==='ui/system/lib/cn.ts'&&x.status==='info'));fs.writeFileSync(path.join(evidence,'doctor-'+MODE+'-normal-evidence.json'),JSON.stringify({host:f.host,bin:f.bin,physicalPackage:f.physical,binResolved:fs.realpathSync(f.bin),coreLock:f.record,artifact,report,npmCalls:fs.readFileSync(f.trace,'utf8')},null,2));});
test('doctor returns actionable uninitialized state without configuration generation',()=>{const f=prepare('uninitialized',{initialized:false});const report=doctor(f,'uninitialized',1);assert.equal(report.status,'uninitialized');assert.ok(report.checks.some(x=>x.code==='config.missing'&&x.path==='hangyeol.json'&&x.action.includes('init')));assert.equal(fs.existsSync(path.join(f.host,'hangyeol.json')),false);});
test('doctor reports missing local source and font asset separately without repair',()=>{const f=prepare('missing');fs.unlinkSync(path.join(f.host,'ui/system/lib/cn.ts'));fs.unlinkSync(path.join(f.host,'static/assets/type/Pretendard-Regular.woff2'));const report=doctor(f,'missing',1);for(const target of ['ui/system/lib/cn.ts','static/assets/type/Pretendard-Regular.woff2'])assert.ok(report.checks.some(x=>x.status==='error'&&x.path===target&&x.code.endsWith('.missing')),target);});

test('doctor rejects malformed config including JSON null and preserves version/record/path safety',()=>{const f=prepare('data-safety'),file=path.join(f.host,'hangyeol.json'),original=fs.readFileSync(file),base=JSON.parse(original);const cases=[['malformed','{','config.json'],['null','null','config.json'],['array','[]','config.json'],['tool-version',JSON.stringify({...base,tool:{...base.tool,version:'0.0.0'}}),'version.config'],['record-missing',JSON.stringify({...base,installed:{...base.installed,[base.sourceRoot+'/lib/cn.ts']:undefined}}),'record.missing'],['record-version',JSON.stringify({...base,installed:{...base.installed,[base.sourceRoot+'/lib/cn.ts']:{...base.installed[base.sourceRoot+'/lib/cn.ts'],version:'0.0.0'}}}),'record.invalid']];assert.equal(cases.length,6);for(const [name,value,code]of cases){fs.writeFileSync(file,value);const report=doctor(f,'data-'+name,1);assert.ok(report.checks.some(x=>x.code===code),name);}
for(const value of ['../outside','/outside','ui\\outside','ui/./system','ui//system','', 'node_modules/runtime','.git/secret']){fs.writeFileSync(file,JSON.stringify({...base,sourceRoot:value}));const report=doctor(f,'unsafe-'+value.replace(/[^a-z]/g,'_'),1);assert.ok(report.checks.some(x=>['path.unsafe','config.path'].includes(x.code)));assert.ok(!JSON.stringify(report).includes(value)||!value||value==='node_modules/runtime');}
fs.writeFileSync(file,JSON.stringify({...base,installed:{...base.installed,'.npmrc':{version:artifact.version,hash:'0'.repeat(64)}}}));const record=doctor(f,'unsafe-record',1);assert.ok(record.checks.some(x=>x.code==='record.path'));assert.ok(!JSON.stringify(record).includes('.npmrc'));fs.writeFileSync(file,original);
const outside=path.join(evidence,'outside-sentinel-'+MODE+'-'+path.basename(f.host));fs.writeFileSync(outside,'OUTSIDE_SECRET_MUST_NOT_BE_READ');const local=path.join(f.host,'ui/system/lib/cn.ts'),bytes=fs.readFileSync(local);fs.unlinkSync(local);fs.symlinkSync(outside,local);const link=doctor(f,'source-symlink',1);assert.ok(link.checks.some(x=>x.code==='path.unsafe'));assert.ok(!JSON.stringify(link).includes('OUTSIDE_SECRET'));assert.ok(!JSON.stringify(link).includes(outside));fs.unlinkSync(local);fs.writeFileSync(local,bytes);
const lockFile=path.join(f.host,'package-lock.json'),lock=fs.readFileSync(lockFile),data=JSON.parse(lock);data.packages['node_modules/@orderthan31/hangyeol-core'].version='0.0.0';fs.writeFileSync(lockFile,JSON.stringify(data));const identity=doctor(f,'core-lock-version',1);assert.ok(identity.checks.some(x=>x.code==='core.identity'));fs.writeFileSync(lockFile,lock);const ok=doctor(f,'safety-restored',0);assert.equal(ok.capabilities.update,false);assert.equal(ok.capabilities.repair,false);});

test('doctor detects broken Tailwind source/theme/font connections while preserving authored CSS',()=>{const f=prepare('connections'),style=path.join(f.host,'styles/theme.css'),fonts=path.join(f.host,'ui/system/foundation/fonts.css'),base=fs.readFileSync(style,'utf8'),fontBase=fs.readFileSync(fonts,'utf8'),cases=[['theme-import',base.replace(/^@import "\.\.\/ui\/system\/foundation\/theme\.css";\n/m,''),fontBase,'connection.stylesheet'],['source-scan',base.replace('@source "../ui/system";','@source "../wrong";'),fontBase,'connection.source'],['preflight',base+'\n@import "tailwindcss/preflight.css";\n',fontBase,'connection.reset'],['font-origin',base,fontBase.replace('/design/assets/type/Pretendard-Regular.woff2','//cdn/assets/type/Pretendard-Regular.woff2'),'connection.fonts'],['font-weight',base,fontBase.replace('font-weight: 400','font-weight: 300'),'connection.fonts']],observed=[];assert.equal(cases.length,5);for(const [name,css,font,code]of cases){fs.writeFileSync(style,css);fs.writeFileSync(fonts,font);const r=run('connection-'+name,f.bin,['doctor'],f.host,f.env);assert.deepEqual(r.after,r.before);observed.push({name,code,...r});}for(const r of observed){assert.equal(r.status,1,r.name+' must not report a broken static connection as healthy');const report=JSON.parse(r.stdout);assert.ok(report.checks.some(x=>x.code===r.code&&x.status==='error'),r.name);}
fs.writeFileSync(style,base+'\n/* Owner style body preserved */\n.owner { --owner-color: #654321; }\n');fs.writeFileSync(fonts,fontBase);fs.appendFileSync(path.join(f.host,'ui/system/foundation/theme.css'),'\n[data-hangyeol] { --g-surface: #654321; --g-danger: rebeccapurple; }\n');const report=doctor(f,'connections-owner-positive',0);const connection=report.checks.find(x=>x.code==='connection.fonts');assert.equal(connection.status,'ok');assert.equal(connection.fonts.length,4);assert.equal(new Set(connection.fonts.map(x=>x.weight)).size,4);for(const font of connection.fonts){const url=new URL(font.url,'https://consumer.invalid/design/');assert.equal(url.origin,'https://consumer.invalid');assert.match(url.pathname,/^\/design\/assets\/type\/Pretendard-/);}assert.equal(fs.readFileSync(f.trace,'utf8'),'');});

test('doctor verifies host config as data and returns unsupported without executing custom modules',()=>{const f=prepare('static-host'),file=path.join(f.host,'vite.config.ts'),original=fs.readFileSync(file,'utf8'),tsfile=path.join(f.host,'tsconfig.json'),tsbase=fs.readFileSync(tsfile),ts=JSON.parse(tsbase),observed=[];const cases=[['base',original.replace('base:"/design/"','base:"/other/"'),1,'connection.vite'],['publicDir',original.replace('publicDir:"static"','publicDir:"wrong"'),1,'connection.vite'],['custom-module','import {writeFileSync} from "node:fs"; writeFileSync("DOCTOR_MUST_NOT_EXECUTE","ran"); export default {};',2,'connection.vite.unsupported'],['custom-plugin',original.replace("import tailwindcss from '@tailwindcss/vite';","import tailwindcss from '@tailwindcss/vite';\nimport custom from './custom-plugin.mjs';").replace('plugins:[tailwindcss()]','plugins:[tailwindcss(),custom()]'),2,'connection.vite.unsupported']];fs.writeFileSync(path.join(f.host,'custom-plugin.mjs'),'import fs from "node:fs";fs.writeFileSync("DOCTOR_MUST_NOT_EXECUTE","plugin ran");export default ()=>({name:"owner"});\n');assert.equal(cases.length,4);for(const [name,content,expected,code]of cases){fs.writeFileSync(file,content);const r=run('host-'+name,f.bin,['doctor'],f.host,f.env);assert.deepEqual(r.after,r.before);assert.equal(fs.existsSync(path.join(f.host,'DOCTOR_MUST_NOT_EXECUTE')),false);observed.push({name,expected,code,...r});}for(const r of observed){assert.equal(r.status,r.expected,r.name);const report=JSON.parse(r.stdout);assert.ok(report.checks.some(x=>x.code===r.code));}fs.writeFileSync(file,original);
ts.compilerOptions.paths['@hangyeol/*']=['./wrong/*'];fs.writeFileSync(tsfile,JSON.stringify(ts));const bad=doctor(f,'ts-alias',1);assert.ok(bad.checks.some(x=>x.code==='connection.typescript'));fs.writeFileSync(tsfile,tsbase);const healthy=doctor(f,'host-restored',0);assert.ok(healthy.checks.some(x=>x.code==='connection.vite'&&x.status==='ok'));assert.ok(healthy.checks.some(x=>x.code==='connection.typescript'&&x.status==='ok'));assert.equal(fs.readFileSync(f.trace,'utf8'),'');});

test('doctor scans actual editable source for forbidden core runtime and broken local imports without executing it',()=>{const f=prepare('runtime-source'),file=path.join(f.host,'ui/system/lib/cn.ts'),original=fs.readFileSync(file,'utf8'),cases=[['core-import','import {main} from "@orderthan31/hangyeol-core/dist/router.mjs";','source.core-runtime',1],['core-dynamic','export const ownerLoad=()=>import("@orderthan31/hangyeol-core/dist/router.mjs");','source.core-runtime',1],['missing-import','import {x} from "./missing-owner-file";','source.import.missing',1],['escaped-import','import {x} from "../../../../OUTSIDE_SECRET_TARGET";','source.import.outside',1],['dynamic-unverified','export const ownerLoad=(name:string)=>import(name);','source.import.dynamic',2]],observed=[];assert.equal(cases.length,5);for(const [name,extra,code,expected]of cases){fs.writeFileSync(file,original+'\n'+extra+'\n');const r=run('runtime-'+name,f.bin,['doctor'],f.host,f.env);assert.deepEqual(r.after,r.before);observed.push({name,code,expected,...r});}for(const r of observed){assert.equal(r.status,r.expected,r.name+' must not report unsupported runtime connection as healthy');const report=JSON.parse(r.stdout),diagnostic=report.checks.find(x=>x.code===r.code&&x.path==='ui/system/lib/cn.ts');assert.ok(diagnostic,r.name);assert.equal(diagnostic.line,original.split('\n').length+1);assert.ok(!JSON.stringify(report).includes('OUTSIDE_SECRET_TARGET'));}
fs.writeFileSync(file,original+'\nexport const ownerHelperMarker="owner-local-helper";\n');const ok=doctor(f,'runtime-local-positive',0);assert.ok(ok.checks.some(x=>x.code==='source.runtime-separation'&&x.status==='ok'));assert.equal(fs.readFileSync(f.trace,'utf8'),'');});

test('doctor checks declared installed and locked runtime/build/type dependencies separately from core tools',()=>{const f=prepare('dependency-data'),pkgFile=path.join(f.host,'package.json'),pkgBase=fs.readFileSync(pkgFile),pkg=JSON.parse(pkgBase),metadata=path.join(f.host,'node_modules/tailwindcss/package.json'),metaBase=fs.readFileSync(metadata),lockFile=path.join(f.host,'package-lock.json'),lockBase=fs.readFileSync(lockFile),observed=[];
for(const name of ['undeclared','tailwind-v3','missing-tailwind','lock-version']){fs.writeFileSync(pkgFile,pkgBase);fs.writeFileSync(metadata,metaBase);fs.writeFileSync(lockFile,lockBase);let code;if(name==='undeclared'){const edited=structuredClone(pkg);delete edited.dependencies.clsx;fs.writeFileSync(pkgFile,JSON.stringify(edited));code='dependency.declared';}if(name==='tailwind-v3'){const edited=structuredClone(pkg);edited.devDependencies.tailwindcss='3.0.0';fs.writeFileSync(pkgFile,JSON.stringify(edited));code='dependency.version';}if(name==='missing-tailwind'){fs.unlinkSync(metadata);code='dependency.missing';}if(name==='lock-version'){const edited=JSON.parse(lockBase);edited.packages['node_modules/clsx'].version='0.0.0';fs.writeFileSync(lockFile,JSON.stringify(edited));code='dependency.lock';}const r=run('dependency-'+name,f.bin,['doctor'],f.host,f.env);assert.deepEqual(r.after,r.before);observed.push({name,code,...r});}assert.equal(observed.length,4);for(const r of observed){assert.equal(r.status,1,r.name);assert.ok(JSON.parse(r.stdout).checks.some(x=>x.code===r.code),r.name);}
fs.writeFileSync(pkgFile,pkgBase);fs.writeFileSync(metadata,metaBase);fs.writeFileSync(lockFile,lockBase);const report=doctor(f,'dependencies-restored',0);assert.deepEqual(report.dependencies.runtime.map(x=>x.name).sort(),['clsx','react','react-dom','tailwind-merge']);assert.deepEqual(report.dependencies.build.map(x=>x.name).sort(),['@tailwindcss/vite','tailwindcss','vite']);assert.deepEqual(report.dependencies.types.map(x=>x.name).sort(),['@types/react','@types/react-dom']);assert.equal(report.dependencies.coreTools.length,4);assert.ok(!report.dependencies.runtime.some(x=>x.name==='@orderthan31/hangyeol-core'||x.name.startsWith('@radix-ui/')));assert.equal(fs.readFileSync(f.trace,'utf8'),'');});

test('doctor retains unknown owner settings and semantic/helper edits without adopting recorded hashes',()=>{const f=prepare('owner-preservation'),file=path.join(f.host,'hangyeol.json'),config=JSON.parse(fs.readFileSync(file)),record=structuredClone(config.installed);config.integration.settings.ownerNote={kept:true};config.owner={palette:'AnyName',color:'rebeccapurple'};config.tokens={palette:'UnregisteredConsumerName',extra:{kept:7}};fs.writeFileSync(file,JSON.stringify(config));for(const [name,extra]of [['lib/cn.ts','\nexport const ownerHelperMarker="local-owner-helper";\n'],['foundation/theme.css','\n[data-hangyeol] { --g-surface: #654321; --g-danger: rebeccapurple; }\n']])fs.appendFileSync(path.join(f.host,'ui/system',name),extra);const report=doctor(f,'owner-preservation',0);assert.equal(report.status,'ok');assert.deepEqual(JSON.parse(fs.readFileSync(file)).installed,record);assert.equal(JSON.parse(fs.readFileSync(file)).integration.settings.ownerNote.kept,true);assert.equal(report.checks.filter(x=>x.code==='source.edited'&&['ui/system/lib/cn.ts','ui/system/foundation/theme.css'].includes(x.path)).length,2);});

test('doctor refuses malformed core lock literals and floating pins instead of claiming installed identity',()=>{const f=prepare('identity-literals'),file=path.join(f.host,'package-lock.json'),original=fs.readFileSync(file),base=JSON.parse(original),pkgfile=path.join(f.host,'package.json'),pkgbase=fs.readFileSync(pkgfile),observed=[];for(const [name,change]of [['integrity',r=>r.integrity='sha512-not-integrity'],['resolved-type',r=>r.resolved=42],['workspace-link',r=>r.link=true]]){const config=structuredClone(base);change(config.packages['node_modules/@orderthan31/hangyeol-core']);fs.writeFileSync(file,JSON.stringify(config));const r=run('identity-'+name,f.bin,['doctor'],f.host,f.env);assert.deepEqual(r.after,r.before);observed.push({name,...r});}for(const r of observed){assert.equal(r.status,1,r.name+' malformed lock identity must fail');assert.ok(JSON.parse(r.stdout).checks.some(x=>x.code==='core.identity'));}fs.writeFileSync(file,original);const pkg=JSON.parse(pkgbase);pkg.devDependencies['@orderthan31/hangyeol-core']='*';fs.writeFileSync(pkgfile,JSON.stringify(pkg));const bad=doctor(f,'floating-dev-pin',1);assert.ok(bad.checks.some(x=>x.code==='core.dev-pin'));fs.writeFileSync(pkgfile,pkgbase);doctor(f,'identity-restored',0);});

test('doctor reports malformed owned theme CSS and TS syntax without replacing owner bytes',()=>{const f=prepare('owned-syntax'),theme=path.join(f.host,'ui/system/foundation/theme.css'),base=fs.readFileSync(theme),cn=path.join(f.host,'ui/system/lib/cn.ts'),helper=fs.readFileSync(cn);fs.writeFileSync(theme,'[data-hangyeol] { --g-surface: pink;\n');const bad=doctor(f,'owned-css-syntax',1);assert.ok(bad.checks.some(x=>x.code==='connection.css'&&x.path==='ui/system/foundation/theme.css'));fs.writeFileSync(theme,base);fs.appendFileSync(cn,'\nexport function broken( {\n');const parsed=doctor(f,'owned-ts-syntax',1);assert.ok(parsed.checks.some(x=>x.code==='source.parse'&&x.path==='ui/system/lib/cn.ts'&&x.line>0));fs.writeFileSync(cn,helper);doctor(f,'owned-syntax-restored',0);});


test('doctor detects TypeScript runtime import-equals core and CLI references',()=>{
  const f=prepare('runtime-import-equals'),file=path.join(f.host,'ui/system/lib/cn.ts'),original=fs.readFileSync(file,'utf8');
  const cases=[['core','import core = require("@orderthan31/hangyeol-core"); export const ownerCore = core;',1,'source.core-runtime'],['cli','import cli = require("@orderthan31/hangyeol-core/tools"); export const ownerCli = cli;',1,'source.core-runtime']],observed=[];
  assert.equal(cases.length,2);
  for(const [name,input,expected,code] of cases){
    const content=original+'\n'+input+'\n',line=original.split('\n').length+1;fs.writeFileSync(file,content);
    const r=run('runtime-import-equals-'+name,f.bin,['doctor'],f.host,f.env);
    assert.deepEqual(r.after,r.before);assert.equal(fs.readFileSync(f.trace,'utf8'),'');
    observed.push({name,input,line,expected,code,...r});
  }
  fs.writeFileSync(path.join(evidence,'doctor-'+MODE+'-runtime-import-equals-outcomes-'+process.hrtime.bigint()+'.json'),JSON.stringify(observed.map(({name,input,line,expected,status,stdout,stderr})=>({name,input,line,expected,actual:status,stdout,stderr})),null,2));
  for(const r of observed){assert.equal(r.status,r.expected,r.name+' runtime import-equals must be rejected');const report=JSON.parse(r.stdout);assert.ok(report.checks.some(c=>c.code===r.code&&c.path==='ui/system/lib/cn.ts'&&c.line===r.line));}
  fs.writeFileSync(file,original);doctor(f,'runtime-import-equals-restored',0);
});


test('doctor distinguishes type-only module references from runtime and retains local path checks',()=>{
  const f=prepare('type-runtime-policy'),file=path.join(f.host,'ui/system/lib/cn.ts'),original=fs.readFileSync(file,'utf8');
  const types=[
    ['type-default','import type Owner from "@orderthan31/hangyeol-core";'],
    ['type-namespace','import type * as Owner from "@orderthan31/hangyeol-core";'],
    ['type-named','import type {Owner} from "@orderthan31/hangyeol-core";'],
    ['all-type-import-specifiers','import {type Owner, type Other} from "@orderthan31/hangyeol-core";'],
    ['type-named-export','export type {Owner} from "@orderthan31/hangyeol-core";'],
    ['type-star-export','export type * from "@orderthan31/hangyeol-core";'],
    ['all-type-export-specifiers','export {type Owner, type Other} from "@orderthan31/hangyeol-core";'],
    ['ts-import-type','export type Owner = import("@orderthan31/hangyeol-core").Owner;'],
    ['ts-import-query','export type Owner = typeof import("@orderthan31/hangyeol-core");'],
    ['type-import-equals','import type Owner = require("@orderthan31/hangyeol-core");'],
    ['type-cli-import-equals','import type Owner = require("@orderthan31/hangyeol-core/tools");'],
    ['type-cli-import','import type {Owner} from "@orderthan31/hangyeol-core/tools";'],
  ];
  const negatives=[
    ['mixed-import','import {type Owner, main} from "@orderthan31/hangyeol-core";',1,'source.core-runtime'],
    ['mixed-export','export {type Owner, main} from "@orderthan31/hangyeol-core";',1,'source.core-runtime'],
    ['mixed-cli-import','import {type Owner, main} from "@orderthan31/hangyeol-core/tools";',1,'source.core-runtime'],
    ['side-effect-import','import "@orderthan31/hangyeol-core";',1,'source.core-runtime'],
    ['empty-import','import {} from "@orderthan31/hangyeol-core";',1,'source.core-runtime'],
    ['runtime-star-export','export * from "@orderthan31/hangyeol-core";',1,'source.core-runtime'],
    ['computed-runtime-import','const ownerName="@orderthan31/hangyeol-core"; export const ownerLoad=()=>import(ownerName);',2,'source.import.dynamic'],
    ['computed-runtime-require','const ownerName="@orderthan31/hangyeol-core"; export const ownerLoad=()=>require(ownerName);',2,'source.import.dynamic'],
    ['computed-import-type','export type Owner = import(ownerName).Owner;',2,'source.import.dynamic'],
    ['type-local-missing','import type {Owner} from "./missing-owner-type";',1,'source.import.missing'],
    ['type-local-import-type-missing','export type Owner = import("./missing-owner-type").Owner;',1,'source.import.missing'],
    ['type-local-equals-missing','import type Owner = require("./missing-owner-type");',1,'source.import.missing'],
    ['type-local-outside','export type Owner = import("../../../../OUTSIDE_OWNER_TYPE").Owner;',1,'source.import.outside'],
  ];
  assert.equal(types.length,12);assert.equal(negatives.length,13);
  const cases=[...types.map(([name,input])=>[name,input,0,null]),...negatives],observed=[];
  for(const [name,input,expected,code] of cases){
    const line=original.split('\n').length+1;fs.writeFileSync(file,original+'\n'+input+'\n');
    const r=run('type-policy-'+name,f.bin,['doctor'],f.host,f.env);
    assert.deepEqual(r.after,r.before);assert.equal(fs.readFileSync(f.trace,'utf8'),'');observed.push({name,input,line,expected,code,...r});
  }
  fs.writeFileSync(path.join(evidence,'doctor-'+MODE+'-type-policy-outcomes-'+process.hrtime.bigint()+'.json'),JSON.stringify(observed.map(({name,input,line,expected,status,stdout,stderr})=>({name,input,line,expected,actual:status,stdout,stderr})),null,2));
  for(const r of observed){
    assert.equal(r.status,r.expected,r.name+' type/runtime policy');const report=JSON.parse(r.stdout);
    if(r.code)assert.ok(report.checks.some(c=>c.code===r.code&&c.path==='ui/system/lib/cn.ts'&&c.line===r.line),r.name+' actual file/line');
    else {assert.ok(!report.checks.some(c=>c.code==='source.core-runtime'),r.name+' is type-only, not runtime coupling');const separation=report.checks.find(c=>c.code==='source.runtime-separation');assert.ok(separation?.imports.some(i=>i.file==='ui/system/lib/cn.ts'&&i.line===r.line&&i.usage==='type-only'),r.name+' type-only reference must be inspected');}
  }
  fs.writeFileSync(file,original);doctor(f,'type-policy-restored',0);
});
