import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const evidence=process.env.CORE07_EVIDENCE_DIR,repo=fileURLToPath(new URL('../../../',import.meta.url));assert.ok(evidence&&path.isAbsolute(evidence)&&path.resolve(evidence)!==path.resolve(repo)&&!path.resolve(evidence).startsWith(path.resolve(repo)+path.sep));
const artifact=JSON.parse(fs.readFileSync(path.join(evidence,'core01-boundary/artifact.json'))),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),json=p=>JSON.parse(fs.readFileSync(p));
function snapshot(dir,base=dir){const s=fs.lstatSync(dir,{bigint:true}),out=dir===base?{'.':{ino:String(s.ino),mtimeNs:String(s.mtimeNs),mode:String(s.mode)}}:{};for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name),st=fs.lstatSync(p,{bigint:true});out[path.relative(base,p)]={ino:String(st.ino),mtimeNs:String(st.mtimeNs),mode:String(st.mode),...(e.isFile()?{hash:sha(fs.readFileSync(p))}:{}),...(e.isSymbolicLink()?{link:fs.readlinkSync(p)}:{})};if(e.isDirectory())Object.assign(out,snapshot(p,base));}return out;}
function run(label,command,args,cwd,expected=0,env=process.env){const before=snapshot(cwd),started=new Date().toISOString(),start=performance.now(),r=spawnSync(command,args,{cwd,env,encoding:'utf8',maxBuffer:16e6}),after=snapshot(cwd);fs.writeFileSync(path.join(evidence,`installed-lint-${label}-${process.hrtime.bigint()}.json`),JSON.stringify({command:[command,...args],cwd,runtime:process.version,started,durationMs:performance.now()-start,exit:r.status,expectedExit:expected,stdout:r.stdout,stderr:r.stderr,before,after},null,2));assert.equal(r.status,expected,r.stdout+'\n'+r.stderr);return {...r,before,after};}
test('physical installed lint checks custom editable UI, exact diagnostics, compiler boundaries and read-only safety',()=>{
 const host=fs.mkdtempSync(path.join(evidence,'installed-lint-host-')),manifest=json(path.join(artifact.unpacked,'package/payload/manifest.json'));
 fs.writeFileSync(path.join(host,'package.json'),JSON.stringify({name:'core07-host',private:true,type:'module',dependencies:{react:'19.2.0','react-dom':'19.2.0',...manifest.runtime},devDependencies:{vite:'7.3.6',...manifest.build,...manifest.types}}));run('offline-physical-install','npm',['install','--offline','--ignore-scripts','--save-dev','--save-exact',artifact.tarball],host);
 const installed=path.join(host,'node_modules/@orderthan31/hangyeol-core'),bin=path.join(host,'node_modules/.bin/hangyeol');assert.equal(fs.lstatSync(installed).isSymbolicLink(),false);assert.equal(fs.realpathSync(bin),path.join(installed,'bin/hangyeol.mjs'));assert.equal(sha(fs.readFileSync(artifact.tarball)),artifact.sha256);assert.equal(run('version',bin,['--version'],host).stdout.trim(),artifact.version);
 const guard=fs.mkdtempSync(path.join(evidence,'lint-npm-guard-')),trace=path.join(guard,'trace');fs.writeFileSync(trace,'');fs.writeFileSync(path.join(guard,'npm'),`#!/bin/sh\nprintf 'unexpected npm\\n' >> '${trace}'\nexit 93\n`);fs.chmodSync(path.join(guard,'npm'),0o755);const env={...process.env,PATH:guard+path.delimiter+process.env.PATH};
 run('init',bin,['init','--source-root','ui/system','--style-path','styles/theme.css','--public-root','static','--font-path','assets/type','--base-path','/design/','--alias','@hangyeol'],host,0,env);run('button',bin,['add','button'],host,0,env);
 function lint(label,expected=0,extra={}){const r=run(label,bin,['lint'],host,expected,{...env,...extra});assert.deepEqual(r.after,r.before,'lint must be fully read-only including config/lock/node_modules');assert.equal(fs.readFileSync(trace,'utf8'),'');return r;}
 const buttonReport=JSON.parse(lint('button-positive').stdout);assert.equal(buttonReport.compiler.mode,'actual');run('text-field',bin,['add','text-field'],host,0,env);
 fs.mkdirSync(path.join(host,'src'));fs.writeFileSync(path.join(host,'src/default-sentinel.tsx'),'export const Sentinel=()=> <div className="hangyeol-not-a-real-utility"/>;');fs.writeFileSync(path.join(host,'eslint.config.mjs'),"throw Error('DO NOT EXECUTE HOST CONFIG');");
 const positive=JSON.parse(lint('textfield-positive').stdout);assert.equal(positive.sourceRoot,'ui/system');assert.equal(positive.coverage.sourceFiles,4);assert.equal(positive.compiler.mode,'actual');assert.equal(positive.compiler.version,'4.3.3');assert.deepEqual(positive.diagnostics,[]);
 const examples=path.join(host,'ui/system/examples');fs.mkdirSync(examples);const target=path.join(examples,'case.tsx'),results=[];
 const cases=[['utility',"export const Bad=()=> <div className=\"p-[13px]\"/>;",'shadcn/no-arbitrary-values'],['unknown',"export const Bad=()=> <div className=\"hangyeol-not-a-real-utility\"/>;",'core/unknown-class'],['override',"import {Button} from '../primitives/button';\nexport const Bad=()=> <Button className=\"p-8 rounded-full\"/>;",'shadcn/no-restyle'],['alias',"import {TextField} from '@hangyeol/components/text-field';\nexport const Bad=()=> <TextField label=\"Name\" className=\"p-8\"/>;",'shadcn/no-restyle'],['namespace',"import * as UI from '../primitives/button';\nexport const Bad=()=> <UI.Button className=\"p-8\"/>;",'shadcn/no-restyle'],['raw',"export const Bad=()=> <div className=\"bg-red-600\"/>;",'shadcn/no-raw-colors'],['inline',"export const Bad=()=> <div style={{padding:13}}/>;",'shadcn/no-inline-styles'],['custom-property',"import {Button} from '../primitives/button';\nexport const Bad=()=> <Button style={{'--g-action':'var(--owner-color)'}}/>;",'ds/no-unowned-custom-properties']];
 for(const [label,code,rule] of cases){fs.writeFileSync(target,code);const r=lint('negative-'+label,1),report=JSON.parse(r.stdout),d=report.diagnostics.find(d=>d.rule===rule);assert.ok(d,report);assert.equal(d.file,'ui/system/examples/case.tsx');assert.equal(d.line,code.startsWith('import')?2:1);assert.match(r.stderr,new RegExp('ui/system/examples/case\\.tsx:'+d.line+':'));results.push({label,diagnostic:d,compiler:report.compiler});}
 fs.writeFileSync(target,"import {Button} from '../primitives/button';\nexport const Good=()=> <Button variant=\"secondary\" size=\"small\" className=\"w-full\"/>;");lint('public-variant-layout-positive');
 fs.appendFileSync(path.join(host,'ui/system/foundation/theme.css'),'\n@theme inline { --color-owner-surface: #123456; --text-owner-body: 1rem; }\n');fs.appendFileSync(path.join(host,'ui/system/lib/cn.ts'),'\n// owner helper edit preserved by lint\n');
 fs.writeFileSync(target,'export const Local=()=> <div className="bg-owner-surface text-owner-body"/>;');const editableTheme=JSON.parse(lint('editable-semantic-theme').stdout);assert.ok(editableTheme.compiler.semantic.colors.includes('owner-surface'));assert.ok(editableTheme.compiler.semantic.text.includes('owner-body'));assert.deepEqual(editableTheme.diagnostics,[]);
 fs.writeFileSync(target,'export const Bad=()=> <div className="bg-red-600"/>;');assert.ok(JSON.parse(lint('raw-palette-after-theme-edit',1).stdout).diagnostics.some(d=>d.rule==='shadcn/no-raw-colors'));
 fs.writeFileSync(target,"import {Button} from '../primitives/button'; export const Good=()=> <Button className=\"w-full\"/>;");
 const reviewCases=[];
 for(const expr of ["'hangyeol-not-a-real-utility' || 'flex'","'hangyeol-not-a-real-utility' ?? 'flex'","cn('hangyeol-not-a-real-utility' || 'flex')"]){fs.writeFileSync(target,`export const View=()=> <div className={${expr}}/>;`);const report=JSON.parse(lint('review-logical-left',1).stdout);assert.ok(report.diagnostics.some(d=>d.rule==='core/unknown-class'&&d.file==='ui/system/examples/case.tsx'&&d.line===1));reviewCases.push({kind:'logical',expr});}
 for(const classes of ['group peer','group/card peer/field','group group-hover:flex peer peer-focus:block','group/card group-hover/card:flex peer/field peer-focus/field:block']){fs.writeFileSync(target,`export const View=()=> <div className="${classes}"/>;`);const report=JSON.parse(lint('review-markers').stdout);assert.deepEqual(report.diagnostics,[]);reviewCases.push({kind:'marker',classes});}
 fs.writeFileSync(target,'export const Bad=()=> <div className="group-invalid peer-invalid"/>;');assert.ok(JSON.parse(lint('review-marker-negative',1).stdout).diagnostics.some(d=>d.rule==='core/unknown-class'));
 fs.writeFileSync(target,'export const Good=()=> <div className="flex"/>;');
 for(const name of ['node_modules','.git','.hangyeol-backups','.hangyeol-transactions']){const dir=path.join(host,'ui/system',name,'nested');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'bad.tsx'),'export const Bad=()=> <div className="hangyeol-not-a-real-utility"/>;');}
 const reserved=JSON.parse(lint('review-nested-reserved').stdout);assert.equal(reserved.coverage.sourceFiles,5);assert.deepEqual(reserved.diagnostics,[]);
 const configFile=path.join(host,'hangyeol.json'),configBytes=fs.readFileSync(configFile),config=JSON.parse(configBytes);
 for(const value of ['../outside','/absolute','ui\\outside','.','']){fs.writeFileSync(configFile,JSON.stringify({...config,sourceRoot:value}));const r=lint('unsafe-config-'+sha(Buffer.from(value)).slice(0,8),1);assert.match(r.stderr,/unsafe|invalid/i);}fs.writeFileSync(configFile,configBytes);
 fs.symlinkSync(path.join(host,'missing'),path.join(host,'dangling'));fs.writeFileSync(configFile,JSON.stringify({...config,sourceRoot:'dangling/ui'}));assert.match(lint('dangling-source',1).stderr,/symlink/i);fs.writeFileSync(configFile,configBytes);
 fs.symlinkSync(path.join(host,'src'),path.join(examples,'linked'));assert.match(lint('linked-child',1).stderr,/symlink/i);fs.unlinkSync(path.join(examples,'linked'));
 const style=path.join(host,'styles/theme.css'),styleBytes=fs.readFileSync(style);const plugin=path.join(host,'plugin.mjs');fs.writeFileSync(plugin,"throw Error('HOST TAILWIND PLUGIN MUST NOT EXECUTE');");fs.appendFileSync(style,'\n@plugin "../plugin.mjs";\n');const blocked=JSON.parse(lint('executable-css-config-unsupported',2).stdout);assert.equal(blocked.compiler.mode,'unavailable');assert.equal(blocked.compiler.fallback,'none');assert.match(blocked.compiler.reason,/@plugin\/@config.*unsupported/);fs.writeFileSync(style,styleBytes);
 // A host components.json must not make the grammar read outside the host.
 const outside=path.join(evidence,'outside-policy-'+process.hrtime.bigint()+'.css'),readTrace=path.join(evidence,'outside-read-'+process.hrtime.bigint()+'.log');fs.writeFileSync(outside,'@theme { --color-owner: red; }\n');fs.writeFileSync(readTrace,'');fs.writeFileSync(path.join(host,'components.json'),JSON.stringify({aliases:{ui:'./ui/system'},tailwind:{css:outside}}));
 const preload=path.join(evidence,'lint-read-trace-'+process.hrtime.bigint()+'.mjs');fs.writeFileSync(preload,`import fs from 'node:fs';import {syncBuiltinESMExports} from 'node:module';const read=fs.readFileSync;fs.readFileSync=function(file,...args){if(String(file)===${JSON.stringify(outside)})fs.appendFileSync(${JSON.stringify(readTrace)},'outside read\\n');return read.call(this,file,...args);};syncBuiltinESMExports();`);
 lint('host-discovery-boundary',0,{NODE_OPTIONS:'--import='+preload});assert.equal(fs.readFileSync(readTrace,'utf8'),'','third-party discovery must not read a host-configured outside stylesheet');
 const policy=json(path.join(installed,'dist/policy/manifest.json'));assert.equal(policy.sourceHash,sha(fs.readFileSync(path.join(repo,'scripts/slice-eslint-policy.mjs'))));assert.deepEqual(fs.readFileSync(path.join(installed,'dist/policy/slice-eslint-policy.mjs')),fs.readFileSync(path.join(repo,'scripts/slice-eslint-policy.mjs')));assert.deepEqual(fs.readFileSync(path.join(installed,'dist/policy/design-jsx-policy.mjs')),fs.readFileSync(path.join(repo,'scripts/design-jsx-policy.mjs')));for(const d of [...policy.dependencies,policy.classifier]){assert.equal(sha(fs.readFileSync(path.join(installed,d.licenseFile))),d.licenseHash);assert.equal(d.license,'MIT');}
 const inspect=JSON.parse(run('lint-inspect',bin,['lint','inspect'],host,0,env).stdout);assert.equal(inspect.dependencies.length,5);const policyFile=path.join(installed,'dist/policy/slice-eslint-policy.mjs'),policyBytes=fs.readFileSync(policyFile);fs.appendFileSync(policyFile,'\n// injected packed policy tamper\n');const tamper=run('policy-tamper',bin,['lint'],host,1,env);assert.deepEqual(tamper.after,tamper.before);assert.match(tamper.stderr,/packed integrity mismatch/);fs.writeFileSync(policyFile,policyBytes);
 const pkg=json(path.join(host,'package.json')),lock=json(path.join(host,'package-lock.json')),core=lock.packages['node_modules/@orderthan31/hangyeol-core'],integrity='sha512-'+crypto.createHash('sha512').update(fs.readFileSync(artifact.tarball)).digest('base64');assert.equal(core.version,artifact.version);assert.equal(core.integrity,integrity);assert.equal(core.dev,true);assert.notEqual(core.link,true);assert.equal(core.resolved,pkg.devDependencies['@orderthan31/hangyeol-core']);assert.equal(lock.packages[''].devDependencies['@orderthan31/hangyeol-core'],pkg.devDependencies['@orderthan31/hangyeol-core']);
 fs.writeFileSync(path.join(evidence,'installed-lint-evidence.json'),JSON.stringify({host,physicalPackage:installed,bin,binResolved:fs.realpathSync(bin),tarball:artifact.tarball,sha256:artifact.sha256,version:artifact.version,integrity,coreLock:core,coreDevPin:pkg.devDependencies['@orderthan31/hangyeol-core'],buttonReport,positive,editableTheme,negativeResults:results,policy,inspect,unsupportedExecutableCSS:blocked,outsideReadTrace:readTrace,outsideReads:fs.readFileSync(readTrace,'utf8'),npmTrace:trace,npmCalls:fs.readFileSync(trace,'utf8'),limits:'prepared offline cache; no empty-cache/VPS/registry/Release or browser proof'},null,2));
});
