import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const evidence=process.env.CORE08_EVIDENCE_DIR,repo=fileURLToPath(new URL('../../../',import.meta.url));
assert.ok(evidence&&path.isAbsolute(evidence)&&path.resolve(evidence)!==path.resolve(repo)&&!path.resolve(evidence).startsWith(path.resolve(repo)+path.sep));
const json=p=>JSON.parse(fs.readFileSync(p)),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),artifact=json(path.join(evidence,'boundary/artifact.json'));
function snapshot(dir,base=dir){const s=fs.lstatSync(dir,{bigint:true}),out={[path.relative(base,dir)||'.']:{inode:String(s.ino),mtimeNs:String(s.mtimeNs),mode:String(s.mode),...(s.isFile()?{hash:sha(fs.readFileSync(dir))}:{}),...(s.isSymbolicLink()?{link:fs.readlinkSync(dir)}:{})}};if(s.isDirectory())for(const e of fs.readdirSync(dir))Object.assign(out,snapshot(path.join(dir,e),base));return out;}
function run(label,command,args,cwd,env=process.env,expected=0,readOnly=false){const before=snapshot(cwd),started=new Date().toISOString(),start=performance.now(),r=spawnSync(command,args,{cwd,env,encoding:'utf8',maxBuffer:16e6}),after=snapshot(cwd);fs.writeFileSync(path.join(evidence,`installed-tokens-${label}-${process.hrtime.bigint()}.json`),JSON.stringify({argv:[command,...args],cwd,runtime:process.version,started,ended:new Date().toISOString(),durationMs:performance.now()-start,exit:r.status,expectedExit:expected,stdout:r.stdout,stderr:r.stderr,before,after},null,2));assert.equal(r.status,expected,r.stdout+'\n'+r.stderr);if(readOnly)assert.deepEqual(after,before,label+' must not mutate consumer');return {...r,before,after};}

test('physical installed tokens validate real consumer schemes, preserve edits, export safely and retain core/lint',()=>{
 const host=fs.mkdtempSync(path.join(evidence,'installed-tokens-host-')),manifest=json(path.join(artifact.unpacked,'package/payload/manifest.json'));
 fs.writeFileSync(path.join(host,'package.json'),JSON.stringify({name:'core08-host',private:true,type:'module',dependencies:{react:'19.2.0','react-dom':'19.2.0',...manifest.runtime},devDependencies:{vite:'7.3.6',...manifest.build,...manifest.types}}));
 run('offline-physical-install','npm',['install','--offline','--ignore-scripts','--save-dev','--save-exact',artifact.tarball],host);
 const installed=path.join(host,'node_modules/@orderthan31/hangyeol-core'),bin=path.join(host,'node_modules/.bin/hangyeol');assert.equal(fs.lstatSync(installed).isSymbolicLink(),false);assert.equal(fs.realpathSync(bin),path.join(installed,'bin/hangyeol.mjs'));assert.equal(sha(fs.readFileSync(artifact.tarball)),artifact.sha256);assert.equal(run('version',bin,['--version'],host).stdout.trim(),artifact.version);assert.equal(fs.existsSync(path.join(host,'ui')),false);
 const guard=fs.mkdtempSync(path.join(evidence,'tokens-npm-guard-')),trace=path.join(guard,'trace');fs.writeFileSync(trace,'');fs.writeFileSync(path.join(guard,'npm'),`#!/bin/sh\nprintf 'npm called\\n' >> '${trace}'\nexit 92\n`);fs.chmodSync(path.join(guard,'npm'),0o755);const env={...process.env,PATH:guard+path.delimiter+process.env.PATH};
 const local=(label,args,expected=0,readOnly=true)=>run(label,bin,args,host,env,expected,readOnly);
 fs.mkdirSync(path.join(host,'styles'));fs.writeFileSync(path.join(host,'styles/theme.css'),'.unrelated-sentinel { color: rebeccapurple; padding: 17px; }\n');
 local('init',['init','--source-root','ui/system','--style-path','styles/theme.css','--public-root','static','--font-path','assets/type','--base-path','/design/','--alias','@hangyeol'],0,false);local('init-noop',['init']);const initialConfigFile=path.join(host,'hangyeol.json'),initialConfig=json(initialConfigFile);initialConfig.owner={kept:['minified',7]};const initialConfigBytes=Buffer.from(JSON.stringify(initialConfig));fs.writeFileSync(initialConfigFile,initialConfigBytes);local('button',['add','button'],0,false);assert.deepEqual(json(initialConfigFile).owner,initialConfig.owner);assert.equal(json(initialConfigFile).installed['ui/system/primitives/button.tsx'].hash,manifest.files['primitives/button.tsx'].hash);const configBackups=Object.keys(snapshot(path.join(host,'.hangyeol-backups'))).filter(name=>name.endsWith('/hangyeol.json')).map(name=>path.join(host,'.hangyeol-backups',name)).filter(file=>fs.readFileSync(file).equals(initialConfigBytes));assert.equal(configBackups.length,1);const metadataBackup={path:configBackups[0],hash:sha(fs.readFileSync(configBackups[0])),originalHash:sha(initialConfigBytes),requiredButtonRecord:json(initialConfigFile).installed['ui/system/primitives/button.tsx']};const buttonLint=jsonResult(local('button-lint',['lint']));assert.equal(buttonLint.compiler.mode,'actual');
 local('textfield',['add','text-field'],0,false);local('textfield-noop',['add','text-field']);const fieldLint=jsonResult(local('textfield-lint',['lint']));assert.deepEqual(fieldLint.diagnostics,[]);
 const original=jsonResult(local('canonical-consumer',['tokens']));assert.equal(original.inputs.length,3);assert.equal(original.schemes.light.roles['--g-action'].value,'#514b83');assert.equal(original.schemes.light.roles['--g-surface'].value,'#FFFFFF');
 const catalogs=jsonResult(local('presets',['tokens','presets']));assert.deepEqual(Object.keys(catalogs.palettes),['Indigo','Silver','Forest','Amber','Rose']);
 const exports=[];for(const name of Object.keys(catalogs.palettes)){
  const stdout=local('preset-stdout-'+name,['tokens','export','--preset',name,'--format','css']);assert.match(stdout.stdout,new RegExp('data-palette="'+name+'"'));assert.match(stdout.stdout,/data-theme="dark"/);
  const target='exports/'+name+'.css',written=jsonResult(local('preset-write-'+name,['tokens','export','--preset',name,'--format','css','--output',target],0,false));assert.equal(sha(fs.readFileSync(path.join(host,target))),written.hash);local('preset-noop-'+name,['tokens','export','--preset',name,'--format','css','--output',target]);exports.push(written);
  const typed=jsonResult(local('preset-json-'+name,['tokens','export','--preset',name]));assert.equal(typed.schemes.dark.roles['--color-g-action'].value,typed.schemes.dark.roles['--g-action'].value);
 }
 const theme=path.join(host,'ui/system/foundation/theme.css'),helper=path.join(host,'ui/system/lib/cn.ts'),configFile=path.join(host,'hangyeol.json'),commonRecord=json(configFile).installed['ui/system/foundation/theme.css'];
 fs.writeFileSync(theme,fs.readFileSync(theme,'utf8').replace('--g-surface: #FFFFFF;','--g-surface: #123456;').replace('--g-surface: #1E293B;','--g-surface: oklch(30% 0.04 270);').replace(/--g-focus: [^;]+;/g,'--g-focus: var(--g-danger);').replace(/--g-danger: [^;]+;/g,'--g-danger: rebeccapurple;')+'\n@theme inline { --spacing-owner: 1.25rem; --color-owner-status: rebeccapurple; }\n');fs.appendFileSync(helper,'\n// consumer helper edit\n');
 const ownerCSS=fs.readFileSync(theme),ownerHelper=fs.readFileSync(helper),actual=jsonResult(local('edited-consumer',['tokens','validate'])),source='ui/system/foundation/tokens.json',palette={replacement:true};
 for(const mode of ['light','dark']){palette[mode]=Object.fromEntries(Object.entries(actual.schemes[mode].roles).map(([name,t])=>[name,{$type:t.type,$value:t.sourceValue}]));palette[mode]['--spacing-owner']={$type:'dimension',$value:1.25,unit:'rem'};palette[mode]['--g-focus']={$type:'color',$value:'{--g-danger}'};palette[mode]['--color-owner-status']={$type:'color',$value:'{--g-danger}'};}
 const config=json(configFile);fs.writeFileSync(path.join(host,source),JSON.stringify({schemaVersion:1,palettes:{Owner:palette}}));fs.writeFileSync(configFile,JSON.stringify({...config,tokens:{source,palette:'Owner'}}));
 const owner=jsonResult(local('owner-source',['tokens','validate']));assert.equal(owner.semanticSource.palettes.Owner.light['--g-surface'].value,'#123456');assert.equal(owner.semanticSource.palettes.Owner.light['--spacing-owner'].unit,'rem');
 local('edited-init-rejected',['init'],1);const connectedAdd=local('edited-common-add-noop',['add','text-field'],0,false);local('unsupported-update-preserved',['update'],1);assert.deepEqual(fs.readFileSync(theme),ownerCSS);assert.deepEqual(fs.readFileSync(helper),ownerHelper);assert.deepEqual(json(configFile).installed['ui/system/foundation/theme.css'],commonRecord);
 const nestedSemanticCases=['[data-hangyeol] { &[data-theme="dark"] { --g-surface: pink; } }','[data-hangyeol] { @media (min-width: 10px) { --g-surface: pink; } }'];assert.equal(nestedSemanticCases.length,2);for(const css of nestedSemanticCases){fs.writeFileSync(theme,ownerCSS.toString()+'\n'+css+'\n');const r=local('nested-semantic-rejected',['tokens','validate'],1);assert.match(r.stderr,/ui\/system\/foundation\/theme\.css:\d+: unsupported semantic nesting/);}fs.writeFileSync(theme,ownerCSS);
 const presetPreservation=[];for(const format of ['json','css']){
  const result=local('owner-silver-'+format,['tokens','export','--preset','Silver','--format',format]);
  if(format==='json'){const selected=jsonResult(result);for(const scheme of ['light','dark']){assert.equal(selected.schemes[scheme].roles['--color-owner-status'].sourceValue,'{--g-danger}');assert.equal(selected.schemes[scheme].roles['--color-owner-status'].alias,'--g-danger');for(const role of ['--g-surface','--g-danger','--spacing-owner'])assert.deepEqual(selected.schemes[scheme].roles[role],owner.semanticSource.palettes.Owner[scheme][role]);assert.equal(selected.schemes[scheme].roles['--color-g-surface'].value,owner.schemes[scheme].roles['--g-surface'].value);assert.equal(selected.schemes[scheme].roles['--g-action'].value,catalogs.palettes.Silver[scheme]['--g-action'].value);presetPreservation.push({format,scheme,surface:selected.schemes[scheme].roles['--g-surface'],danger:selected.schemes[scheme].roles['--g-danger']});}}
  else{assert.match(result.stdout,/--color-owner-status: var\(--g-danger\);/);const cssHost=fs.mkdtempSync(path.join(evidence,'silver-css-host-'));fs.mkdirSync(path.join(cssHost,'ui/system'),{recursive:true});fs.writeFileSync(path.join(cssHost,'silver.css'),result.stdout);fs.writeFileSync(path.join(cssHost,'hangyeol.json'),JSON.stringify({schemaVersion:1,sourceRoot:'ui/system',stylePath:'silver.css'}));const parsed=jsonResult(run('owner-silver-css-parity',bin,['tokens','validate','--palette','Silver'],cssHost,env,0,true));for(const scheme of ['light','dark']){for(const role of ['--g-surface','--g-danger','--spacing-owner'])assert.equal(parsed.schemes[scheme].roles[role].value,owner.schemes[scheme].roles[role].value);assert.equal(parsed.schemes[scheme].roles['--color-g-surface'].value,parsed.schemes[scheme].roles['--g-surface'].value);assert.equal(parsed.schemes[scheme].roles['--color-g-action'].value,parsed.schemes[scheme].roles['--g-action'].value);}fs.writeFileSync(path.join(cssHost,'silver.css'),result.stdout.replace(/--g-danger: rebeccapurple;/g,'--g-danger: tomato;'));const changed=jsonResult(run('linked-export-danger-edit',bin,['tokens','validate','--palette','Silver'],cssHost,env,0,true));for(const scheme of ['light','dark'])assert.equal(changed.schemes[scheme].roles['--color-owner-status'].value,'tomato');assert.match(result.stdout,/--g-surface: #123456;/);assert.match(result.stdout,/--g-surface: oklch\(30% 0.04 270\);/);for(const scheme of ['light','dark'])assert.ok(result.stdout.includes('--g-danger: '+owner.schemes[scheme].roles['--g-danger'].value+';'));assert.match(result.stdout,/--color-g-surface: var\(--g-surface\)/);assert.match(result.stdout,/--spacing-owner: 1.25rem/);presetPreservation.push({format,bothSchemes:true,hash:sha(Buffer.from(result.stdout))});}
 }
 const exported=jsonResult(local('owner-export',['tokens','export']));assert.equal(exported.schemes.light.roles['--color-owner-status'].alias,'--g-danger');assert.equal(exported.schemes.dark.roles['--color-owner-status'].sourceValue,'{--g-danger}');assert.match(local('owner-no-preset-alias-css',['tokens','export','--format','css']).stdout,/--color-owner-status: var\(--g-danger\);/);assert.equal(exported.schemes.light.roles['--g-focus'].value,owner.schemes.light.roles['--g-danger'].value);assert.equal(exported.schemes.light.roles['--spacing-owner'].value,'1.25rem');
 const sourceFile=path.join(host,source),valid=fs.readFileSync(sourceFile),negatives=[['missing',p=>delete p.light['--g-surface'],/missing role/],['type',p=>p.light['--g-surface'].$type='dimension',/type mismatch/],['cycle',p=>{p.light['--g-surface'].$value='{--g-ink}';p.light['--g-ink'].$value='{--g-surface}';},/alias cycle/],['target',p=>p.light['--g-surface'].$value='{--g-absent}',/missing alias target/],['parity',p=>p.light['--g-danger'].$value='pink',/parity mismatch/]];assert.equal(negatives.length,5);
 for(const [name,modify,reason]of negatives){const p=structuredClone(palette);modify(p);fs.writeFileSync(sourceFile,JSON.stringify({schemaVersion:1,palettes:{Owner:p}}));const r=local('negative-'+name,['tokens','validate'],1);assert.match(r.stderr,reason);}fs.writeFileSync(sourceFile,valid);
 const badOutputs=['../escape','/absolute','bad\\path','exports/./bad.css','node_modules/tokens.css','hangyeol.json','package.json','package-lock.json',source,'ui/system/new.css','styles/theme.css','static/new.css'];assert.equal(badOutputs.length,12);for(const output of badOutputs)local('unsafe-output',['tokens','export','--output',output],1);
 fs.symlinkSync(path.join(host,'absent'),path.join(host,'dangling'));assert.match(local('symlink-output',['tokens','export','--output','dangling/tokens.css'],1).stderr,/symlink/);assert.match(local('symlink-source',['tokens','validate','--source','dangling/tokens.json'],1).stderr,/symlink/);
 local('traversal-source',['tokens','validate','--source','../outside.json'],1);local('unknown-palette',['tokens','validate','--palette','Absent'],1);local('unknown-preset',['tokens','export','--preset','Absent'],1);
 const target=path.join(host,'exports/Owner.json'),write=jsonResult(local('explicit-owner-write',['tokens','export','--output','exports/Owner.json'],0,false));assert.equal(write.hash,sha(fs.readFileSync(target)));local('identical-owner-export',['tokens','export','--output','exports/Owner.json']);fs.appendFileSync(target,'\n// owner export edit\n');local('edited-export-rejected',['tokens','export','--output','exports/Owner.json'],1);
 const finalLint=jsonResult(local('edited-values-lint',['lint']));assert.equal(finalLint.compiler.mode,'actual');assert.deepEqual(finalLint.diagnostics,[]);
 fs.writeFileSync(path.join(host,'index.html'),'<div id="root"></div><script type="module" src="/main.tsx"></script>');fs.writeFileSync(path.join(host,'main.tsx'),`import {createRoot} from 'react-dom/client';import {TextField} from './ui/system/components/text-field';import './styles/theme.css';import './exports/Indigo.css';createRoot(document.getElementById('root')!).render(<div data-hangyeol="" data-palette="Indigo"><TextField label="local token consumption" defaultValue="owner value"/></div>);`);
 const ts=json(path.join(host,'tsconfig.json'));Object.assign(ts.compilerOptions,{target:'ES2022',lib:['ES2022','DOM'],module:'ESNext',moduleResolution:'Bundler',jsx:'react-jsx',strict:true,skipLibCheck:true,noEmit:true,types:['vite/client']});ts.include=['main.tsx','ui/system/**/*.tsx','ui/system/**/*.ts'];fs.writeFileSync(path.join(host,'tsconfig.json'),JSON.stringify(ts));run('host-typecheck',path.join(host,'node_modules/.bin/tsc'),['--pretty','false'],host,env);run('host-vite-build',path.join(host,'node_modules/.bin/vite'),['build'],host,env);
 const css=fs.readdirSync(path.join(host,'dist/assets')).filter(n=>n.endsWith('.css')).map(n=>fs.readFileSync(path.join(host,'dist/assets',n),'utf8')).join('\n');assert.match(css,/#514b83/i);assert.match(css,/#123456/i);assert.match(css,/unrelated-sentinel/);assert.doesNotMatch(fs.readFileSync(path.join(host,'styles/theme.css'),'utf8'),/preflight|@import "tailwindcss"/);assert.deepEqual(fs.readFileSync(theme),ownerCSS);assert.deepEqual(fs.readFileSync(helper),ownerHelper);
 const pkg=json(path.join(host,'package.json')),lock=json(path.join(host,'package-lock.json')),record=lock.packages['node_modules/@orderthan31/hangyeol-core'],integrity='sha512-'+crypto.createHash('sha512').update(fs.readFileSync(artifact.tarball)).digest('base64');assert.equal(record.version,artifact.version);assert.equal(record.integrity,integrity);assert.equal(record.dev,true);assert.notEqual(record.link,true);assert.equal(record.resolved,pkg.devDependencies['@orderthan31/hangyeol-core']);assert.equal(lock.packages[''].devDependencies['@orderthan31/hangyeol-core'],pkg.devDependencies['@orderthan31/hangyeol-core']);assert.equal(fs.readFileSync(trace,'utf8'),'');
 const policy=path.join(installed,'dist/tools/token-policy.mjs');assert.deepEqual(fs.readFileSync(policy),fs.readFileSync(path.join(repo,'packages/core/src/tools/token-policy.mjs')));const bytes=fs.readFileSync(policy);fs.appendFileSync(policy,'\n// tamper\n');assert.match(local('token-policy-tamper',['tokens','validate'],1).stderr,/packed integrity mismatch/);fs.writeFileSync(policy,bytes);
 fs.writeFileSync(path.join(evidence,'installed-tokens-evidence.json'),JSON.stringify({host,bin,binResolved:fs.realpathSync(bin),physicalPackage:installed,tarball:artifact.tarball,sha256:artifact.sha256,integrity,version:artifact.version,coreDevPin:pkg.devDependencies['@orderthan31/hangyeol-core'],coreLock:record,exports,owner,exported,presetPreservation,nestedSemanticCases,metadataBackup,buttonLint,fieldLint,finalLint,generatedCSSHash:sha(Buffer.from(css)),npmTrace:trace,npmCalls:fs.readFileSync(trace,'utf8'),positiveSchemes:10,negativeSemanticCases:negatives.map(c=>c[0]),unsafeOutputCount:badOutputs.length,unmet:['init remains conflict-preserving on edited theme, not a success/noop update','update unsupported with byte-preserving exit 1','Docs Reset is state-only; not exercised','nested/portal arbitrary palette propagation, native focus and unrelated computed style not browser verified','browser runtime/portal/default verification pending separate actual execution'],limits:['prepared cache only; no VPS/empty-cache/registry/Release','static grammar/cascade subset, not browser/AT/contrast certification']},null,2));
 // P1: retain the exact connected acceptance assertion from the original RED.
 assert.deepEqual(connectedAdd.after,connectedAdd.before,'repeated add must preserve consumer-authored config bytes/mtime/backups');
});
function jsonResult(r){return JSON.parse(r.stdout);}

test('physical installed bin rejects both inherited prototype preset names before any output/npm',()=>{
 const host=fs.mkdtempSync(path.join(evidence,'prototype-installed-host-'));fs.writeFileSync(path.join(host,'package.json'),JSON.stringify({name:'core08-prototype-host',private:true,type:'module'}));run('prototype-offline-install','npm',['install','--offline','--ignore-scripts','--save-dev','--save-exact',artifact.tarball],host);
 const installed=path.join(host,'node_modules/@orderthan31/hangyeol-core'),bin=path.join(host,'node_modules/.bin/hangyeol');assert.equal(fs.lstatSync(installed).isSymbolicLink(),false);assert.equal(fs.realpathSync(bin),path.join(installed,'bin/hangyeol.mjs'));assert.equal(sha(fs.readFileSync(artifact.tarball)),artifact.sha256);
 fs.mkdirSync(path.join(host,'ui/system/foundation'),{recursive:true});fs.copyFileSync(path.join(installed,'payload/source/foundation/theme.css'),path.join(host,'ui/system/foundation/theme.css'));fs.writeFileSync(path.join(host,'theme.css'),'@import "./ui/system/foundation/theme.css";\n');fs.writeFileSync(path.join(host,'hangyeol.json'),JSON.stringify({schemaVersion:1,sourceRoot:'ui/system',stylePath:'theme.css',owner:{preserved:true}}));
 const guard=fs.mkdtempSync(path.join(evidence,'prototype-npm-guard-')),trace=path.join(guard,'trace');fs.writeFileSync(trace,'');fs.writeFileSync(path.join(guard,'npm'),`#!/bin/sh\nprintf 'npm called\\n' >> '${trace}'\nexit 92\n`);fs.chmodSync(path.join(guard,'npm'),0o755);const env={...process.env,PATH:guard+path.delimiter+process.env.PATH},cases=['constructor','__proto__'],observed=[];assert.equal(cases.length,2);
 for(const name of cases){const args=['tokens','export','--preset',name,'--output','exports/'+name+'.json'],before=snapshot(host),started=new Date().toISOString(),start=performance.now(),r=spawnSync(bin,args,{cwd:host,env,encoding:'utf8'}),after=snapshot(host),row={name,argv:[bin,...args],cwd:host,runtime:process.version,started,ended:new Date().toISOString(),durationMs:performance.now()-start,exit:r.status,stdout:r.stdout,stderr:r.stderr,before,after};fs.writeFileSync(path.join(evidence,`installed-prototype-${name}-${process.hrtime.bigint()}.json`),JSON.stringify(row,null,2));observed.push(row);}
 for(const r of observed){assert.equal(r.exit,1,r.name+' must be explicitly rejected');assert.match(r.stderr,new RegExp('Unknown preset '+r.name+'; no fallback'));assert.deepEqual(r.after,r.before);assert.equal(fs.existsSync(path.join(host,'exports',r.name+'.json')),false);}assert.equal(fs.readFileSync(trace,'utf8'),'');
 const pkg=json(path.join(host,'package.json')),lock=json(path.join(host,'package-lock.json')),record=lock.packages['node_modules/@orderthan31/hangyeol-core'],integrity='sha512-'+crypto.createHash('sha512').update(fs.readFileSync(artifact.tarball)).digest('base64');assert.equal(record.version,artifact.version);assert.equal(record.integrity,integrity);assert.equal(record.dev,true);assert.notEqual(record.link,true);assert.equal(record.resolved,pkg.devDependencies['@orderthan31/hangyeol-core']);assert.equal(lock.packages[''].devDependencies['@orderthan31/hangyeol-core'],pkg.devDependencies['@orderthan31/hangyeol-core']);fs.writeFileSync(path.join(evidence,'prototype-installed-evidence.json'),JSON.stringify({host,bin,binResolved:fs.realpathSync(bin),artifact,record,integrity,coreDevPin:pkg.devDependencies['@orderthan31/hangyeol-core'],npmTrace:trace,npmCalls:fs.readFileSync(trace,'utf8'),cases:observed.map(r=>({name:r.name,exit:r.exit,stderr:r.stderr,snapshotsEqual:JSON.stringify(r.before)===JSON.stringify(r.after)}))},null,2));
});

async function physicalTokenFixture(label){
 const host=fs.mkdtempSync(path.join(evidence,label+'-host-'));fs.writeFileSync(path.join(host,'package.json'),JSON.stringify({name:'core08-'+label,private:true,type:'module',devDependencies:{tailwindcss:'4.3.3'}}));run(label+'-offline-install','npm',['install','--offline','--ignore-scripts','--save-dev','--save-exact',artifact.tarball],host);const installed=path.join(host,'node_modules/@orderthan31/hangyeol-core'),bin=path.join(host,'node_modules/.bin/hangyeol');assert.equal(fs.lstatSync(installed).isSymbolicLink(),false);assert.equal(fs.realpathSync(bin),path.join(installed,'bin/hangyeol.mjs'));assert.equal(sha(fs.readFileSync(artifact.tarball)),artifact.sha256);const pkg=json(path.join(host,'package.json')),lock=json(path.join(host,'package-lock.json')),record=lock.packages['node_modules/@orderthan31/hangyeol-core'],integrity='sha512-'+crypto.createHash('sha512').update(fs.readFileSync(artifact.tarball)).digest('base64');assert.equal(record.version,artifact.version);assert.equal(record.integrity,integrity);assert.equal(record.dev,true);assert.notEqual(record.link,true);assert.equal(record.resolved,pkg.devDependencies['@orderthan31/hangyeol-core']);assert.equal(lock.packages[''].devDependencies['@orderthan31/hangyeol-core'],pkg.devDependencies['@orderthan31/hangyeol-core']);fs.mkdirSync(path.join(host,'ui/system/foundation'),{recursive:true});fs.copyFileSync(path.join(installed,'payload/source/foundation/theme.css'),path.join(host,'ui/system/foundation/theme.css'));fs.writeFileSync(path.join(host,'theme.css'),'@import "./ui/system/foundation/theme.css";\n');fs.writeFileSync(path.join(host,'hangyeol.json'),JSON.stringify({schemaVersion:1,sourceRoot:'ui/system',stylePath:'theme.css',owner:{preserved:true}}));const guard=fs.mkdtempSync(path.join(evidence,label+'-npm-guard-')),trace=path.join(guard,'trace');fs.writeFileSync(trace,'');fs.writeFileSync(path.join(guard,'npm'),`#!/bin/sh\nprintf 'npm called\\n' >> '${trace}'\nexit 92\n`);fs.chmodSync(path.join(guard,'npm'),0o755);const env={...process.env,PATH:guard+path.delimiter+process.env.PATH};return {host,installed,bin,trace,env,record,integrity,coreDevPin:pkg.devDependencies['@orderthan31/hangyeol-core'],local:(name,args,expected=0)=>run(label+'-'+name,bin,args,host,env,expected,true)};
}
test('physical linked scheme aliases retain JSON and inline utility CSS target/edit meaning',async()=>{
 const f=await physicalTokenFixture('scheme'),{host,bin,local,env}=f,theme=path.join(host,'ui/system/foundation/theme.css');fs.writeFileSync(theme,fs.readFileSync(theme,'utf8').replace(/--g-(danger|overlay): [^;]+;/g,'--g-$1: rebeccapurple;')+'\n@theme inline { --color-owner-status: rebeccapurple; }\n');const css=fs.readFileSync(theme,'utf8'),current=jsonResult(local('current',['tokens'])),palette={replacement:true};for(const mode of ['light','dark']){palette[mode]=Object.fromEntries(Object.entries(current.schemes[mode].roles).map(([n,t])=>[n,{$type:t.type,$value:t.sourceValue}]));palette[mode]['--color-owner-status']={$type:'color',$value:mode==='light'?'{--g-danger}':'{--g-overlay}'};}const source='ui/system/foundation/tokens.json';fs.writeFileSync(path.join(host,source),JSON.stringify({schemaVersion:1,palettes:{Owner:palette}}));fs.writeFileSync(path.join(host,'hangyeol.json'),JSON.stringify({...json(path.join(host,'hangyeol.json')),tokens:{source,palette:'Owner'}}));const original=snapshot(host),observed=[],{default:postcss}=await import('postcss');
 for(const preset of [null,'Silver'])for(const scheme of [null,'dark']){const args=[...(preset?['--preset',preset]:[]),...(scheme?['--scheme',scheme]:[])],typed=jsonResult(local('json',['tokens','export',...args]));for(const mode of scheme?[scheme]:['light','dark'])assert.equal(typed.schemes[mode].roles['--color-owner-status'].alias,mode==='light'?'--g-danger':'--g-overlay');const r=local('css',['tokens','export',...args,'--format','css']),ast=postcss.parse(r.stdout);let edits=0;ast.walkRules(rule=>{if(rule.selector.includes('data-theme="dark"'))for(const d of rule.nodes??[])if(d.type==='decl'&&d.prop==='--g-overlay'){d.value='tomato';edits++;}});assert.equal(edits,1);const consumer=fs.mkdtempSync(path.join(evidence,'physical-scheme-export-'));fs.mkdirSync(path.join(consumer,'ui'));fs.writeFileSync(path.join(consumer,'hangyeol.json'),JSON.stringify({schemaVersion:1,sourceRoot:'ui',stylePath:'export.css'}));fs.writeFileSync(path.join(consumer,'export.css'),(scheme?css+'\n':'')+ast.toString());const parsed=jsonResult(run('physical-scheme-overlay-edit',bin,['tokens','validate','--palette',preset??'Owner'],consumer,env,0,true));observed.push({preset,scheme,css:r.stdout,roles:parsed.schemes});}
 assert.equal(observed.length,4);for(const r of observed){assert.equal(r.roles.dark.roles['--color-owner-status'].value,'tomato','physical exported dark alias must follow overlay');if(!r.scheme)assert.equal(r.roles.light.roles['--color-owner-status'].value,'rebeccapurple');}
 const {createRequire}=await import('node:module'),require=createRequire(path.join(host,'package.json')),{compile}=require('tailwindcss');const compiler=[];for(const r of observed){const out=(await compile(r.css+'\n@tailwind utilities;\n')).build(['text-owner-status']);assert.match(out,/\.text-owner-status/);assert.match(out,/color: var\(--(?:g-export-color-owner-status|g-overlay)\)/);compiler.push({preset:r.preset,scheme:r.scheme,css:out,hash:sha(Buffer.from(out))});}assert.deepEqual(snapshot(host),original);assert.equal(fs.readFileSync(f.trace,'utf8'),'');fs.writeFileSync(path.join(evidence,'scheme-physical-evidence.json'),JSON.stringify({host,bin,binResolved:fs.realpathSync(bin),version:artifact.version,sha256:artifact.sha256,record:f.record,integrity:f.integrity,coreDevPin:f.coreDevPin,npmCalls:'',observed,compiler,compilerMode:'actual installed host Tailwind 4.3.3 compile/build; browser deferred'},null,2));
});

test('physical consumer selector diagnostics distinguish compound from descendants without writes/npm',async()=>{
 const f=await physicalTokenFixture('selector'),theme=path.join(f.host,'ui/system/foundation/theme.css'),original=fs.readFileSync(theme,'utf8'),cases=['[data-hangyeol] [data-theme="dark"]','[data-hangyeol]\t[data-theme="dark"]','[data-hangyeol]\n[data-theme="dark"]','[data-hangyeol] > [data-theme="dark"]','[data-hangyeol]+[data-theme="dark"]','[data-hangyeol]~[data-theme="dark"]'],observed=[];assert.equal(cases.length,6);
 for(const selector of cases){fs.writeFileSync(theme,original+'\n'+selector+' { --g-surface: pink; }\n');const before=snapshot(f.host),started=new Date().toISOString(),start=performance.now(),r=spawnSync(f.bin,['tokens','validate'],{cwd:f.host,env:f.env,encoding:'utf8'}),after=snapshot(f.host),row={selector,argv:[f.bin,'tokens','validate'],cwd:f.host,runtime:process.version,started,ended:new Date().toISOString(),durationMs:performance.now()-start,exit:r.status,stdout:r.stdout,stderr:r.stderr,before,after};fs.writeFileSync(path.join(evidence,'installed-selector-negative-'+process.hrtime.bigint()+'.json'),JSON.stringify(row,null,2));observed.push(row);}
 for(const r of observed){assert.equal(r.exit,1,r.selector+' must be refused');assert.match(r.stderr,/ui\/system\/foundation\/theme\.css:\d+: unsupported semantic selector structure/);assert.deepEqual(r.after,r.before);}
 const positives=['[data-hangyeol][data-theme="dark"]','[ data-hangyeol ][ data-theme = "dark" ]','[data-hangyeol][data-theme = dark]'];for(const selector of positives){fs.writeFileSync(theme,original+'\n'+selector+' { --g-surface: pink; }\n.sentinel > .child { color: tomato; }\n.sentinel { &:hover { color: pink; } }\n');const r=jsonResult(f.local('compound',['tokens']));assert.equal(r.schemes.dark.roles['--g-surface'].value,'pink');assert.equal(r.schemes.light.roles['--g-surface'].value,'#FFFFFF');}assert.equal(positives.length,3);assert.equal(fs.readFileSync(f.trace,'utf8'),'');fs.writeFileSync(path.join(evidence,'selector-physical-evidence.json'),JSON.stringify({host:f.host,bin:f.bin,binResolved:fs.realpathSync(f.bin),version:artifact.version,sha256:artifact.sha256,record:f.record,integrity:f.integrity,coreDevPin:f.coreDevPin,negativeCases:observed.map(r=>({selector:r.selector,exit:r.exit,stderr:r.stderr,snapshotsEqual:JSON.stringify(r.before)===JSON.stringify(r.after)})),positiveCases:positives,npmCalls:''},null,2));
});

test('physical scoped typed namespaces preserve scheme cascade and refuse knownType-only combinators',async()=>{
 const f=await physicalTokenFixture('typed-scope'),theme=path.join(f.host,'ui/system/foundation/theme.css'),original=fs.readFileSync(theme,'utf8');fs.writeFileSync(theme,original+'\n@theme inline { --color-owner: rebeccapurple; --font-owner: Alpha; --text-owner: 1rem; --radius-owner: 2px; --spacing-owner: 3px; }\n[data-hangyeol] { --g-danger: var(--color-owner); }\n[data-hangyeol][data-theme="dark"] { --color-owner: pink; --font-owner: Beta; --text-owner: 2rem; --radius-owner: 4px; --spacing-owner: 5px; }\n.host > .child { color: tomato; }\n');const report=jsonResult(f.local('validate',['tokens']));assert.equal(report.schemes.dark.roles['--g-danger'].value,'pink');assert.equal(report.schemes.light.roles['--g-danger'].value,'rebeccapurple');const expected={'--color-owner':'pink','--font-owner':'Beta','--text-owner':'2rem','--radius-owner':'4px','--spacing-owner':'5px'};assert.equal(Object.keys(expected).length,5);for(const [name,value]of Object.entries(expected))assert.equal(report.schemes.dark.roles[name].value,value);const exported=f.local('css',['tokens','export','--format','css']);fs.writeFileSync(theme,exported.stdout);assert.equal(jsonResult(f.local('roundtrip',['tokens'])).schemes.dark.roles['--g-danger'].value,'pink');
 const selectors=['[data-hangyeol] [data-theme="dark"]','[data-hangyeol]\t[data-theme="dark"]','[data-hangyeol]\n[data-theme="dark"]','[data-hangyeol]>[data-theme="dark"]','[data-hangyeol]+[data-theme="dark"]'];assert.equal(selectors.length,5);const observed=[];for(const selector of selectors){fs.writeFileSync(theme,original+'\n'+selector+' { --color-owner: pink; }\n');const r=f.local('structure',['tokens','export','--output','exports/rejected.json'],1);assert.match(r.stderr,/ui\/system\/foundation\/theme\.css:\d+: unsupported semantic selector structure/);observed.push({selector,exit:r.status,stderr:r.stderr,snapshotsEqual:true});}assert.equal(fs.readFileSync(f.trace,'utf8'),'');fs.writeFileSync(path.join(evidence,'typed-scope-physical-evidence.json'),JSON.stringify({host:f.host,bin:f.bin,binResolved:fs.realpathSync(f.bin),artifact,record:f.record,integrity:f.integrity,coreDevPin:f.coreDevPin,report,observed,npmCalls:''},null,2));
});

test('physical repeated semantic attributes fail read-only including declaration-free registration',async()=>{
 const f=await physicalTokenFixture('duplicates'),theme=path.join(f.host,'ui/system/foundation/theme.css'),original=fs.readFileSync(theme,'utf8'),cases=[['[data-hangyeol][data-theme="light"][data-theme="dark"]','--g-surface: pink;','theme'],['[data-hangyeol][data-palette="A"][data-palette="B"]','--g-surface: pink;','palette'],["[ data-hangyeol ][ data-theme = 'light' ][ data-theme = dark ]",'--g-surface: pink;','theme'],['[data-hangyeol][data-theme="dark"][data-theme="dark"]','--g-surface: pink;','theme'],['[data-hangyeol][data-palette="A"][data-palette="B"][data-theme="dark"]','','palette'],["[ data-hangyeol ][ data-palette = 'A' ][ data-palette = B ]",'','palette']],observed=[];assert.equal(cases.length,6);
 for(const [selector,decl,attribute]of cases){fs.writeFileSync(theme,original+'\n'+selector+' { '+decl+' }\n');const args=['tokens','export','--output','exports/rejected-'+observed.length+'.json'],before=snapshot(f.host),started=new Date().toISOString(),start=performance.now(),r=spawnSync(f.bin,args,{cwd:f.host,env:f.env,encoding:'utf8'}),after=snapshot(f.host),row={selector,attribute,argv:[f.bin,...args],cwd:f.host,runtime:process.version,started,ended:new Date().toISOString(),durationMs:performance.now()-start,exit:r.status,stdout:r.stdout,stderr:r.stderr,before,after};fs.writeFileSync(path.join(evidence,'installed-duplicate-'+process.hrtime.bigint()+'.json'),JSON.stringify(row,null,2));observed.push(row);}for(const r of observed){assert.equal(r.exit,1,r.selector+' must reject repeated attribute');assert.match(r.stderr,new RegExp('ui/system/foundation/theme\\.css:\\d+: duplicate semantic '+r.attribute+' attribute'));assert.deepEqual(r.after,r.before);}
 const positives=["[ data-hangyeol ][ data-palette = 'Owner' ][ data-theme = dark ]",'[data-hangyeol][data-theme="dark"][data-palette="Owner"]','[data-hangyeol][data-palette="Owner"]'];assert.equal(positives.length,3);for(const selector of positives){fs.writeFileSync(theme,original+'\n'+selector+' { }\n.host[data-palette="Other"] { color: pink; }\n');assert.ok(jsonResult(f.local('registration',['tokens','validate','--palette','Owner'])).declaredPalettes.includes('Owner'));}assert.equal(fs.readFileSync(f.trace,'utf8'),'');fs.writeFileSync(path.join(evidence,'duplicates-physical-evidence.json'),JSON.stringify({host:f.host,bin:f.bin,binResolved:fs.realpathSync(f.bin),artifact,record:f.record,integrity:f.integrity,coreDevPin:f.coreDevPin,negativeCases:observed.map(r=>({selector:r.selector,exit:r.exit,stderr:r.stderr,snapshotsEqual:true})),positiveCases:positives,npmCalls:''},null,2));
});

test('physical repeated imports retain source order and active cycles reject before output/npm',async()=>{
 const f=await physicalTokenFixture('import-order');fs.writeFileSync(path.join(f.host,'override.css'),'[data-hangyeol] { --g-surface: pink; }\n');fs.writeFileSync(path.join(f.host,'theme.css'),'@import "./ui/system/foundation/theme.css";\n@import "./override.css";\n@import "./ui/system/foundation/theme.css";\n.host { color: tomato; }\n');const report=jsonResult(f.local('repeat',['tokens','export']));assert.equal(report.schemes.light.roles['--g-surface'].value,'#FFFFFF');assert.equal(report.schemes.dark.roles['--g-surface'].value,'#1E293B');assert.deepEqual(report.inputs.map(i=>i.path),['theme.css','ui/system/foundation/theme.css','override.css','ui/system/foundation/theme.css']);assert.equal(report.inputs[1].hash,report.inputs[3].hash);const css=f.local('css',['tokens','export','--format','css']);assert.match(css.stdout,/--g-surface: #FFFFFF/);assert.match(css.stdout,/--g-surface: #1E293B/);fs.writeFileSync(path.join(f.host,'override.css'),'@import "./theme.css";\n');const bad=f.local('cycle',['tokens','export','--output','exports/rejected.json'],1);assert.match(bad.stderr,/CSS import cycle: theme\.css -> override\.css -> theme\.css/);assert.equal(fs.readFileSync(f.trace,'utf8'),'');fs.writeFileSync(path.join(evidence,'imports-physical-evidence.json'),JSON.stringify({host:f.host,bin:f.bin,binResolved:fs.realpathSync(f.bin),artifact,record:f.record,integrity:f.integrity,coreDevPin:f.coreDevPin,report,css:css.stdout,cycle:{exit:bad.status,stderr:bad.stderr,snapshotsEqual:true},npmCalls:''},null,2));
});

test('physical imports reject unsupported ancestor grammar before reading targets without output npm or mutations',async()=>{
 const f=await physicalTokenFixture('import-context'),style=path.join(f.host,'theme.css'),base=fs.readFileSync(style,'utf8');fs.writeFileSync(path.join(f.host,'override.css'),'[data-hangyeol] { --g-surface: pink; }\n');const cases=['@media (min-width:800px) { @import "./override.css"; }','@supports (display:grid) { @import "./override.css"; }','@container owner (width>1px) { @import "./override.css"; }','@media (min-width:800px) { @layer owner { @import "./override.css"; } }','.host { @import "./override.css"; }','.host { @supports (display:grid) { @import "./override.css"; } }','@theme inline { @import "./override.css"; }','@unknown { @import "./override.css"; }','@media (min-width:800px) { @import "./missing.css"; }'],observed=[];assert.equal(cases.length,9);
 for(const css of cases){fs.writeFileSync(style,base+'\n'+css+'\n');const args=['tokens','export','--output','exports/rejected-'+observed.length+'.json'],before=snapshot(f.host),started=new Date().toISOString(),start=performance.now(),r=spawnSync(f.bin,args,{cwd:f.host,env:f.env,encoding:'utf8'}),after=snapshot(f.host),row={inputCSS:base+'\n'+css+'\n',argv:[f.bin,...args],cwd:f.host,runtime:process.version,started,ended:new Date().toISOString(),durationMs:performance.now()-start,exit:r.status,stdout:r.stdout,stderr:r.stderr,before,after};fs.writeFileSync(path.join(evidence,'installed-import-context-'+process.hrtime.bigint()+'.json'),JSON.stringify(row,null,2));observed.push(row);}for(const r of observed){assert.equal(r.exit,1,r.inputCSS);assert.match(r.stderr,/theme\.css:\d+: unsupported CSS import context/);assert.doesNotMatch(r.stderr,/ENOENT/);assert.deepEqual(r.after,r.before);}
 const positives=['@import "./override.css";','@import "./override.css" layer(owner);','@layer owner { @import "./override.css"; }','@layer owner { @layer inner { @import "./override.css"; } }'];assert.equal(positives.length,4);for(const css of positives){fs.writeFileSync(style,base+'\n'+css+'\n@media (min-width:800px) { .host { color: pink; } }\n.host { @supports (display:grid) { color: tomato; } }\n');assert.equal(jsonResult(f.local('positive',['tokens'])).schemes.light.roles['--g-surface'].value,'pink');}
 fs.writeFileSync(style,base+'\n@supports (display:grid) { [data-hangyeol] { --g-surface: pink; } }\n');assert.match(f.local('direct-semantic',['tokens'],1).stderr,/unsupported conditional\/nested semantic @supports/);assert.equal(fs.readFileSync(f.trace,'utf8'),'');fs.writeFileSync(path.join(evidence,'import-context-physical-evidence.json'),JSON.stringify({host:f.host,bin:f.bin,binResolved:fs.realpathSync(f.bin),artifact,record:f.record,integrity:f.integrity,coreDevPin:f.coreDevPin,negatives:observed.map(r=>({inputCSS:r.inputCSS,exit:r.exit,stderr:r.stderr,snapshotsEqual:true})),positives,npmCalls:''},null,2));
});

test('physical theme parameters refuse unsupported forms while empty inline and layer arrangements pass',async()=>{
 const f=await physicalTokenFixture('theme-params'),theme=path.join(f.host,'ui/system/foundation/theme.css'),base=fs.readFileSync(theme,'utf8'),params=['reference','static','default','inline reference','inline inline','owner'],observed=[];assert.equal(params.length,6);for(const value of params){const inputCSS=base+'\n@theme '+value+' { --color-owner: pink; }\n';fs.writeFileSync(theme,inputCSS);const args=['tokens','export','--output','exports/rejected-'+observed.length+'.json'],before=snapshot(f.host),started=new Date().toISOString(),start=performance.now(),r=spawnSync(f.bin,args,{cwd:f.host,env:f.env,encoding:'utf8'}),after=snapshot(f.host),row={inputCSS,value,argv:[f.bin,...args],cwd:f.host,runtime:process.version,started,ended:new Date().toISOString(),durationMs:performance.now()-start,exit:r.status,stdout:r.stdout,stderr:r.stderr,before,after};fs.writeFileSync(path.join(evidence,'installed-theme-params-'+process.hrtime.bigint()+'.json'),JSON.stringify(row,null,2));observed.push(row);}for(const r of observed){assert.equal(r.exit,1,r.value);assert.match(r.stderr,/ui\/system\/foundation\/theme\.css:\d+: unsupported @theme parameters/);assert.deepEqual(r.after,r.before);}
 const positives=['@theme { --color-owner: pink; }','@theme   inline { --color-owner: pink; }','@layer owner { @theme inline { --color-owner: pink; } }'];assert.equal(positives.length,3);for(const css of positives){fs.writeFileSync(theme,base+'\n'+css+'\n');assert.equal(jsonResult(f.local('positive',['tokens'])).schemes.light.roles['--color-owner'].value,'pink');}assert.equal(fs.readFileSync(f.trace,'utf8'),'');fs.writeFileSync(path.join(evidence,'theme-params-physical-evidence.json'),JSON.stringify({host:f.host,bin:f.bin,binResolved:fs.realpathSync(f.bin),artifact,record:f.record,integrity:f.integrity,coreDevPin:f.coreDevPin,negatives:observed.map(r=>({value:r.value,exit:r.exit,stderr:r.stderr,snapshotsEqual:true})),positives,npmCalls:''},null,2));
});
test('physical direct semantic placement refuses silent omission and retains host only CSS',async()=>{
 const f=await physicalTokenFixture('placement'),theme=path.join(f.host,'ui/system/foundation/theme.css'),base=fs.readFileSync(theme,'utf8'),cases=['@layer owner { --g-surface: pink; }','@layer owner { --color-owner: pink; }','--font-owner: Owner;','@layer owner { --text-owner: 1rem; }','@layer owner { --radius-owner: 2px; }','@layer owner { --spacing-owner: 3px; }','--g-owner-note: kept;','@supports (display:grid) { --g-surface: pink; }','@font-face { --g-surface: pink; }','@theme inline { --g-owner-note: kept; }'],observed=[];assert.equal(cases.length,10);for(const css of cases){const inputCSS=base+'\n'+css+'\n';fs.writeFileSync(theme,inputCSS);const args=['tokens','export','--output','exports/rejected-'+observed.length+'.json'],before=snapshot(f.host),started=new Date().toISOString(),start=performance.now(),r=spawnSync(f.bin,args,{cwd:f.host,env:f.env,encoding:'utf8'}),after=snapshot(f.host),row={inputCSS,argv:[f.bin,...args],cwd:f.host,runtime:process.version,started,ended:new Date().toISOString(),durationMs:performance.now()-start,exit:r.status,stdout:r.stdout,stderr:r.stderr,before,after};fs.writeFileSync(path.join(evidence,'installed-placement-'+process.hrtime.bigint()+'.json'),JSON.stringify(row,null,2));observed.push(row);}for(const r of observed){assert.equal(r.exit,1,r.inputCSS);assert.match(r.stderr,/ui\/system\/foundation\/theme\.css:\d+: unsupported semantic declaration placement/);assert.deepEqual(r.after,r.before);}
 fs.writeFileSync(theme,base+'\n@layer owner { .host { color: pink; } }\n@media (min-width:800px) { .host { color: tomato; } }\n@font-face { font-family: Owner; src: url("local.woff2"); }\n[data-hangyeol] { --g-owner-note: kept; }\n');assert.equal(jsonResult(f.local('host-only',['tokens'])).schemes.light.roles['--g-owner-note'].sourceValue,'kept');assert.equal(fs.readFileSync(f.trace,'utf8'),'');fs.writeFileSync(path.join(evidence,'placement-physical-evidence.json'),JSON.stringify({host:f.host,bin:f.bin,binResolved:fs.realpathSync(f.bin),artifact,record:f.record,integrity:f.integrity,coreDevPin:f.coreDevPin,negatives:observed.map(r=>({inputCSS:r.inputCSS,exit:r.exit,stderr:r.stderr,snapshotsEqual:true})),npmCalls:''},null,2));
});
