type ComponentContent = { when: string; preview: string };
export const componentContent: Record<string, ComponentContent> = {
  Badge: { when: '짧은 상태나 분류를 표시할 때 사용합니다. 클릭해서 실행하는 행동에는 Button을 사용하세요.', preview: '세 가지 tone과 본문 안에서의 배치를 비교합니다. 색상과 함께 상태 문구가 남는지 확인하세요.' },
  Button: { when: '현재 화면에서 작업을 실행할 때 사용합니다. 페이지 이동은 링크로 구분하세요.', preview: 'primary·secondary·quiet의 우선순위, 두 가지 크기, loading과 disabled 상태를 비교합니다.' },
  Input: { when: '라벨과 안내를 화면에서 직접 조합할 때 사용합니다. 한 묶음의 입력이 필요하면 TextField를 사용하세요.', preview: '이메일 입력을 수정하고 readOnly와 disabled에서 편집 가능 여부를 비교합니다.' },
  TextField: { when: '라벨, 입력값과 안내를 일관된 구조로 보여줘야 하는 폼에 사용합니다.', preview: '초기값을 내부에서 관리하는 이름 입력과 화면에서 관리하는 이메일 입력, 지우기와 오류 안내를 비교합니다.' },
  Select: { when: '선택지가 정해져 있고 목록을 접어 둘 때 사용합니다. 검색이 필요하면 Combobox, 전체 비교가 중요하면 RadioGroup이 적합합니다.', preview: '정렬 기준을 고르면 아래 목록의 순서가 바뀝니다. 사용할 수 없는 선택지도 함께 확인하세요.' },
  Tabs: { when: '같은 맥락의 내용을 여러 보기로 나눌 때 사용합니다. 입력값 하나를 고르는 용도로는 SegmentedControl을 사용하세요.', preview: '제품 정보·배송·리뷰의 연결된 패널과 가로·세로 방향, 선택 상태와 키보드 이동을 확인합니다.' },
  Dialog: { when: '사용자가 현재 작업을 잠시 멈추고 확인하거나 입력해야 할 때 사용합니다. 가벼운 보조 설정은 Popover로 구분하세요.', preview: '삭제 확인을 열고 취소하거나 완료해 보세요. 완료 후 트리거가 비활성화되는 경우의 초점 복귀 위치도 지정한 예제입니다.' },
  FormSection: { when: '긴 폼을 목적별 입력 묶음으로 나눌 때 사용합니다. 모든 입력을 독립된 카드로 만들 필요는 없습니다.', preview: '프로필과 연락처 입력의 제목·설명·제출 행동을 같은 form 안에 조합합니다.' },
  Layout: { when: '세로 읽기 흐름 안에 가로 행동 묶음을 조합할 때 사용합니다.', preview: 'Stack 안에 라벨·입력·설명을 놓고 Row로 저장·취소 행동을 묶습니다. 간격 옵션은 바깥 배치에만 적용됩니다.' },
  Row: { when: '같은 수준의 버튼이나 정보를 가로로 묶을 때 사용합니다.', preview: '저장·취소 버튼 사이의 간격을 변경합니다. 가로 공간이 부족하면 다음 줄로 배치됩니다.' },
  Stack: { when: '제목·입력·설명처럼 순서가 있는 내용을 세로로 배치할 때 사용합니다.', preview: '입력과 설명, 버튼 사이의 간격을 바꿉니다. 입력의 내부 여백과 부모 간격은 별개입니다.' },
  List: { when: '반복되는 내용을 하나의 목록으로 읽게 할 때 사용합니다.', preview: '항목 사이의 divider와 빈 목록을 비교합니다. 목록 데이터와 빈 상태 안내는 화면에서 전달합니다.' },
  ListItem: { when: 'List 안에 한 항목의 제목, 설명과 필요한 보조 행동을 놓을 때 사용합니다.', preview: '배송 알림의 본문과 버튼을 조합합니다. 행 전체가 자동으로 클릭 가능한 버튼이 되지는 않습니다.' },
  ListPanel: { when: '목록의 제목, 보조 행동, 내용과 하단 안내를 함께 구성할 때 사용합니다.', preview: '알림 목록의 일반·빈 상태·불러오는 중 상태를 비교합니다. 조회나 데이터 요청은 포함하지 않습니다.' },
  Checkbox: { when: '여러 항목을 독립적으로 고르거나 동의 여부를 확인할 때 사용합니다.', preview: '선택·미선택·일부 선택 상태와 비활성 상태를 비교하고, 선택값이 폼에 포함되는 조건을 확인합니다.' },
  Switch: { when: '하나의 설정을 켜거나 끄는 의미가 명확할 때 사용합니다.', preview: '설정의 켜짐·꺼짐과 비활성 상태를 비교합니다. 실제 저장은 사용하는 화면의 정책에 연결하세요.' },
  Textarea: { when: '여러 줄의 글을 입력할 때 사용합니다. 한 줄 입력은 Input이나 TextField로 구분하세요.', preview: '입력 내용, 오류 안내, readOnly와 disabled를 비교하고 폼 초기화를 확인합니다.' },
  Slider: { when: '범위 안의 값이나 구간을 조절할 때 사용합니다. 정확한 숫자 입력이 필요하면 NumberInput을 함께 고려하세요.', preview: '손잡이 하나의 값과 두 손잡이의 범위, 비활성 상태와 방향키 조작을 확인합니다.' },
  Progress: { when: '작업의 진행 정도를 알 수 있을 때 사용합니다. 수치를 모르면 불확정 상태로 표시하세요.', preview: '현재 값이 있는 진행 막대와 진행량을 모르는 상태를 비교합니다.' },
  Separator: { when: '서로 다른 내용 묶음을 선으로 구분해야 할 때 사용합니다. 여백만으로 구분되면 생략할 수 있습니다.', preview: '가로와 세로 구분선의 방향을 비교합니다. 조작하는 요소는 아닙니다.' },
  Skeleton: { when: '불러올 내용의 구조가 정해져 있어 자리를 먼저 보여줄 때 사용합니다.', preview: '텍스트·원형·블록 자리표시자와 실제 내용으로 전환되는 모습을 확인합니다.' },
  LoadingSpinner: { when: '작업이 진행 중이지만 남은 양을 알 수 없을 때 사용합니다.', preview: '진행 안내와 실제 내용을 전환합니다. 반복 낭독을 줄이려면 장식용 표시와 상태 안내를 구분하세요.' },
  Container: { when: '페이지 본문의 최대 너비와 좌우 여백을 공통 기준에 맞출 때 사용합니다.', preview: 'reading·content·wide·full의 최대 너비를 비교합니다. 화면이 좁으면 부모 너비 안으로 줄어듭니다.' },
  Grid: { when: '같은 수준의 항목을 화면 너비에 따라 여러 열로 놓을 때 사용합니다.', preview: '1~4열 설정을 바꿉니다. 실제 열 수는 화면 너비에 따라 바뀌며 작은 화면은 1열에서 시작합니다.' },
  Highlight: { when: '검색어가 문장 안에서 일치하는 위치를 보여줄 때 사용합니다.', preview: '검색어를 바꾸고 대소문자 구분을 비교합니다. 입력한 검색어는 정규식이나 HTML로 해석하지 않습니다.' },
  Icon: { when: '행동이나 상태를 작은 그림으로 보조할 때 사용합니다.', preview: '제공 아이콘의 크기와 이름을 확인합니다. 장식용 아이콘과 정보를 전달하는 아이콘의 접근 이름을 구분하세요.' },
  IconButton: { when: '반복되는 도구 행동처럼 아이콘만으로 공간을 줄여야 할 때 사용합니다.', preview: '아이콘을 바꾸고 클릭, loading과 disabled를 비교합니다. 보이는 글자가 없어도 label은 필요합니다.' },
  FormField: { when: 'Input 외의 입력도 공통 라벨·안내·오류 구조로 연결해야 할 때 사용합니다.', preview: '라벨과 설명을 실제 입력에 연결하고 오류 표시를 비교합니다. 사용자 정의 입력에는 전달받은 접근성 속성을 적용하세요.' },
  ActionGroup: { when: '같은 작업의 주요 행동과 보조 행동을 함께 배치할 때 사용합니다.', preview: '저장·취소 행동의 정렬을 비교합니다. 버튼 상태와 실제 행동은 각 버튼에 연결합니다.' },
  ListHeader: { when: '목록의 제목, 항목 수와 보조 행동을 묶어서 보여줄 때 사용합니다.', preview: '제목·설명·항목 수·행동 버튼의 배치를 확인합니다. 항목 수를 직접 계산하거나 데이터를 가져오지는 않습니다.' },
  ListFooter: { when: '목록 아래에 요약이나 다음 페이지 행동을 놓을 때 사용합니다.', preview: '하단 정보와 추가 행동의 정렬을 확인합니다. 데이터 추가 요청은 화면에서 연결합니다.' },
  EmptyState: { when: '항목이 없을 때 원인과 가능한 다음 행동을 안내하는 데 사용합니다.', preview: '빈 상태의 제목·설명·행동을 확인합니다. 검색 결과 없음과 아직 생성한 항목 없음은 문구를 다르게 작성하세요.' },
  AddressField: { when: '우편번호·기본 주소·상세 주소를 하나의 입력 묶음으로 다룰 때 사용합니다.', preview: '예시 주소 선택 후 상세 주소 입력과 제출 필드 구성을 확인합니다. 실제 주소 검색 서비스는 연결하지 않았습니다.' },
  CheckboxGroup: { when: '여러 선택지를 한눈에 보여주고 여러 개를 고르게 할 때 사용합니다.', preview: '개별 선택·전체 선택·일부 선택과 제출 배열을 확인합니다. 비활성 항목은 전체 선택에서 제외됩니다.' },
  CurrencyInput: { when: '금액을 읽기 쉽게 표시하면서 원래 숫자 문자열을 관리할 때 사용합니다.', preview: '화면의 쉼표 표시와 제출되는 원래 값을 비교합니다. 이 예제는 원 단위 정수 입력입니다.' },
  EmailInput: { when: '이메일에 맞는 기본 입력 속성을 적용한 TextField가 필요할 때 사용합니다.', preview: '이메일 입력, 지우기, 읽기 전용과 오류를 확인합니다. 주소의 실제 존재 여부는 확인하지 않습니다.' },
  FileInput: { when: '업로드할 파일을 고르고 선택 결과를 확인할 때 사용합니다.', preview: '다중 파일 선택, 파일당 크기 제한과 선택 지우기를 확인합니다. 파일을 서버로 전송하지 않습니다.' },
  NumberInput: { when: '정확한 숫자를 입력하거나 정해진 단계로 값을 바꾸게 할 때 사용합니다.', preview: '0~20 범위에서 직접 입력과 증감 버튼, 읽기 전용·비활성 상태를 비교합니다.' },
  PasswordInput: { when: '비밀번호를 숨긴 채 입력하고 필요할 때만 확인하게 할 때 사용합니다.', preview: '표시 전환, 입력 초점과 readOnly·disabled를 확인합니다. 비밀번호 강도를 평가하지는 않습니다.' },
  PhoneInput: { when: '국내 전화번호의 표시 형식과 저장 값을 구분할 때 사용합니다.', preview: '화면의 하이픈 표시와 제출값을 비교합니다. 국제번호나 실제 가입 여부 확인은 포함하지 않습니다.' },
  Rating: { when: '사용자가 정수 점수로 만족도나 평가를 입력할 때 사용합니다.', preview: '별 선택과 방향키 이동, 읽기 전용·비활성 상태, 제출 점수를 확인합니다.' },
  SearchField: { when: '검색어 입력과 검색 실행을 연결할 때 사용합니다.', preview: 'Enter로 전달되는 검색어와 지우기를 확인합니다. 결과 목록과 검색 통신은 화면에서 구현합니다.' },
  RadioGroup: { when: '선택지를 모두 보여주고 하나를 비교·선택하게 할 때 사용합니다.', preview: '단일 선택, 필수 선택과 비활성 항목을 비교하고 제출값을 확인합니다.' },
  SegmentedControl: { when: '짧고 관련 있는 선택값을 버튼 묶음으로 바꿀 때 사용합니다.', preview: '표시 기간 선택과 선택 해제 허용 여부를 비교합니다. 연결된 콘텐츠 패널을 전환하는 Tabs와는 다릅니다.' },
  Combobox: { when: '선택지가 많고 이름으로 검색한 뒤 하나를 고르게 할 때 사용합니다.', preview: '검색어와 확정한 선택값의 차이, 방향키·Enter 선택, 필수 선택과 지우기를 확인합니다.' },
  MultiSelect: { when: '많은 선택지를 접힌 목록에 두고 여러 개 고르게 할 때 사용합니다.', preview: '선택 태그, 개별 해제와 최대 선택 수를 비교합니다. 제출은 같은 name의 여러 값입니다.' },
  IconAction: { when: '아이콘 행동에 보조 설명이나 보이는 이름을 함께 제공할 때 사용합니다.', preview: '아이콘과 이름 표시, 툴팁, loading·disabled를 비교합니다. 클릭 횟수만 표시하고 실제 저장은 하지 않습니다.' },
  Popover: { when: '현재 화면을 막지 않는 간단한 설정이나 추가 정보를 펼칠 때 사용합니다.', preview: '표시 옵션을 열고 설정을 바꾼 뒤 닫아 보세요. 화면 전체의 확인이 필요하면 Dialog를 사용합니다.' },
  Alert: { when: '현재 화면에서 알아야 할 안내나 처리 결과를 알릴 때 사용합니다.', preview: '안내·완료·주의·오류 의미와 닫기 동작을 비교합니다.' },
  Breadcrumb: { when: '계층이 있는 화면에서 현재 위치와 상위 이동 경로를 보여줄 때 사용합니다.', preview: '상위 링크·현재 위치·긴 경로의 줄바꿈을 확인합니다.' },
  Bubble: { when: '작성자와 시각이 있는 짧은 대화·의견 내용을 묶을 때 사용합니다.', preview: '왼쪽·오른쪽 배치와 답장 행동을 확인하며 실제 메시지를 전송하지 않습니다.' },
  ErrorState: { when: '작업을 이어가지 못했을 때 원인 안내와 다시 시도할 행동을 제공할 때 사용합니다.', preview: '추가 안내·다시 시도·외부 처리 중 상태를 확인합니다. 실제 요청은 하지 않습니다.' },
  Pagination: { when: '목록을 여러 페이지로 나누고 현재 페이지를 바꿀 때 사용합니다.', preview: '번호·생략 표시·이전/다음·비활성 상태를 확인합니다.' },
  ProgressStepper: { when: '여러 단계로 된 작업에서 현재 위치와 진행 상태를 보여줄 때 사용합니다.', preview: '단계를 선택해 완료·현재·예정 상태의 변화를 확인합니다.' },
  Result: { when: '작업을 마친 뒤 완료·오류 결과와 다음 행동을 정리해서 보여줄 때 사용합니다.', preview: '완료·안내·오류와 다음으로·다시 시도 행동을 비교합니다.' },
  Table: { when: '같은 항목을 행과 열로 비교해야 할 때 사용합니다.', preview: '표 제목·열 제목·숫자 정렬과 긴 자료 이름을 확인합니다.' },
  Menu: { when: "Menu·MenuTrigger·MenuContent·MenuItem을 조합합니다. onSelect에 실제 행동을 연결하고 사용할 수 없는 항목은 disabled로 막으세요.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  Accordion: { when: "type=single은 하나, multiple은 여러 항목을 펼칩니다. single에서 collapsible을 켜면 열린 항목도 닫을 수 있습니다. value·onValueChange 또는 defaultValue로 상태를 관리하세요.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  Collapse: { when: "한 덩어리의 추가 내용을 펼칠 때 사용합니다. Root의 open·onOpenChange 또는 defaultOpen으로 상태를 관리합니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  Confirm: { when: "trigger에는 Button 같은 하나의 요소, title·description에는 확인할 행동과 결과를 넣습니다. 기본 초점은 취소에 놓이고 외부 영역을 눌러 승인하지 않습니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  Drawer: { when: "Drawer는 Dialog를 바탕으로 현재 작업 옆에 패널을 여는 조합입니다. DrawerTrigger·DrawerContent를 넣고 title로 패널 이름을 지정합니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  BottomSheet: { when: "BottomSheet·BottomSheetTrigger·BottomSheetContent로 아래쪽 패널을 구성합니다. title과 description으로 작업을 설명하고 actions를 하단 행동으로 분리합니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  ListRow: { when: "native li이므로 List 또는 ul 안에 넣습니다. title·description·leading·actions로 내용을 나눕니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  GridList: { when: "items·getKey·renderItem을 전달합니다. 각 항목은 native ul/li이며 columns는 1·2·3·4입니다. 화면 폭에 맞게 열을 줄입니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  GNB: { when: "logo·items·actions를 전달합니다. 로고는 프로젝트의 CI를 넣을 수 있는 자리이며 공용 컴포넌트에 특정 브랜드 자산을 고정하지 않습니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  LNB: { when: "items의 id·label·href·children으로 영역별 경로를 구성합니다. children이 있으면 native details로 펼칩니다. disabled 항목은 실행하지 않습니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  Shell: { when: "header·sidebar·children에 실제 GNB·LNB와 본문을 전달합니다. 제품의 경로나 권한을 공용 source에 고정하지 않습니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  BottomCTA: { when: "children에 한두 개의 실제 Button을 넣습니다. ActionGroup의 줄바꿈과 정렬을 사용하고 disabled·loading은 각 버튼에서 관리합니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  Toast: { when: "ToastProvider 안에서 useToast().notify로 title·description을 전달합니다. 자동 종료는 기본 5초이며 duration을 바꿀 수 있습니다.", preview: "예제의 실제 행동과 펼침·선택·비활성 상태를 확인합니다. 서버에 저장하지 않습니다." },
  DatePicker: { when: "YYYY-MM-DD 날짜-only 문자열을 사용합니다. 직접 입력한 값은 그대로 유지하고 잘못된 날짜·윤년·min/max·선택 불가 날짜를 오류로 표시합니다. UTC나 시간대로 변환하지 않습니다.", preview: "현재 값·선택 범위·오류와 실제 예제 행동을 확인합니다. 서버 자료는 변경하지 않습니다." },
  MonthPicker: { when: "YYYY-MM 형식으로 월만 선택합니다. 일(day)이나 임의의 날짜를 붙이지 않습니다. 직접 입력·연도 이동·월 grid·지우기를 제공합니다.", preview: "현재 값·선택 범위·오류와 실제 예제 행동을 확인합니다. 서버 자료는 변경하지 않습니다." },
  TimeInput: { when: "HH:mm의 24시간 문자열을 직접 입력하거나 시·분 Select로 고릅니다. 시간대 변환은 하지 않습니다. 기본 1분 간격이며 step의 단위는 분입니다.", preview: "현재 값·선택 범위·오류와 실제 예제 행동을 확인합니다. 서버 자료는 변경하지 않습니다." },
  DateTimeInput: { when: "value는 {date: YYYY-MM-DD, time: HH:mm}입니다. DatePicker와 TimeInput의 직접 입력·선택·오류·clear를 조합합니다.", preview: "현재 값·선택 범위·오류와 실제 예제 행동을 확인합니다. 서버 자료는 변경하지 않습니다." },
  DateRangePicker: { when: "value는 {start: YYYY-MM-DD, end: YYYY-MM-DD}입니다. 달력에서 시작·끝을 순서대로 선택하며 끝이 비어 있을 때 포인터 위치로 범위를 미리 보여 줍니다.", preview: "현재 값·선택 범위·오류와 실제 예제 행동을 확인합니다. 서버 자료는 변경하지 않습니다." },
  DataTable: { when: "data·columns·getKey로 실제 행과 열을 전달합니다. 각 column의 value는 검색·필터·정렬에 쓰고 render는 셀 표현에 사용합니다. sortable로 정렬할 열을 지정하세요.", preview: "현재 값·선택 범위·오류와 실제 예제 행동을 확인합니다. 서버 자료는 변경하지 않습니다." },
  Chart: { when: "실제 data·labelKey·series를 전달하고 kind로 line·bar·donut을 고릅니다. Recharts 한 엔진을 사용하며 임의의 샘플 값을 내부에서 만들지 않습니다.", preview: "현재 값·선택 범위·오류와 실제 예제 행동을 확인합니다. 서버 자료는 변경하지 않습니다." },
  Tooltip: { when: '기존 요소의 이름을 바꾸지 않고 짧은 보조 설명을 덧붙일 때 사용합니다.', preview: '마우스나 초점으로 표시되는 설명과 지연 시간을 확인합니다. 중요한 안내는 본문에도 남겨야 합니다.' },
};
const introductionChoices: Record<string, 'lead' | 'context'> = {
  "Badge": "lead",
  "Button": "context",
  "Input": "context",
  "TextField": "context",
  "Select": "context",
  "Tabs": "context",
  "Dialog": "context",
  "FormSection": "context",
  "ActionGroup": "lead",
  "Checkbox": "context",
  "Switch": "context",
  "Textarea": "context",
  "Slider": "context",
  "Separator": "context",
  "Skeleton": "context",
  "LoadingSpinner": "context",
  "Container": "context",
  "Highlight": "lead",
  "Icon": "context",
  "IconButton": "context",
  "FormField": "context",
  "EmptyState": "lead",
  "CheckboxGroup": "context",
  "CurrencyInput": "lead",
  "FileInput": "context",
  "NumberInput": "context",
  "PasswordInput": "context",
  "Rating": "context",
  "SearchField": "context",
  "RadioGroup": "context",
  "Combobox": "lead",
  "MultiSelect": "context",
  "Alert": "context",
  "Breadcrumb": "context",
  "Bubble": "context",
  "ErrorState": "context",
  "Table": "context"
};
const previewNotes: Record<string, string> = {
  "Layout": "간격 옵션은 바깥 배치에만 적용됩니다.",
  "CurrencyInput": "이 예제는 원 단위 정수 입력입니다.",
  "NumberInput": "이 예제는 0~20 범위의 정수를 입력합니다.",
  "PasswordInput": "비밀번호 강도를 평가하지는 않습니다.",
  "ErrorState": "실제 요청은 하지 않습니다.",
  "Drawer": "서버에 저장하지 않습니다.",
  "BottomSheet": "서버에 저장하지 않습니다.",
  "DatePicker": "서버 자료는 변경하지 않습니다.",
  "MonthPicker": "서버 자료는 변경하지 않습니다.",
  "TimeInput": "서버 자료는 변경하지 않습니다.",
  "DateTimeInput": "서버 자료는 변경하지 않습니다.",
  "DateRangePicker": "서버 자료는 변경하지 않습니다.",
  "DataTable": "서버 자료는 변경하지 않습니다.",
  "Chart": "서버 자료는 변경하지 않습니다."
};
export function ComponentIntroduction({ name, description, leadClassName }: { name: string; description: string; leadClassName: string }) {
  const choice = introductionChoices[name];
  if (!choice) return null;
  return <p className={choice === 'lead' ? leadClassName : 'docs-component-context'}>{choice === 'lead' ? description : componentContent[name].when}</p>;
}
export function ExamplePurpose({ name }: { name: string }) {
  const note = previewNotes[name];
  return note ? <p className="docs-example-purpose">{note}</p> : null;
}
